### ISSUE TITLE
Permit duplicate domain definitions if metadata exists to allow it

### ISSUE THREAD

**Issue by jasoncuriano** [StackExchange/dnscontrol#1017]
As a dnscontrol user, I'd like to be able to declare multiple D() for the same FQDN. For our use case, we use Route53 for external DNS, and BIND for internal DNS, with separate records and subdomains for the external vs internal zones.

I'd like to be able to deploy this use case via a js file along these lines:
```js
var REG_NONE = NewRegistrar('none', 'NONE');
var AXFRDDNS = NewDnsProvider('axfrddns', 'AXFRDDNS');
var R53 = NewDnsProvider('R53', 'ROUTE53');

// Internal DNS served by BIND
D("example.com", REG_NONE, DnsProvider(AXFRDDNS), 
    A("foo", "1.2.3.4"),
    A("bar", "1.2.3.5")
);
D_EXTEND("internal_sub.example.com",
    A("abc", "1.2.3.6")
);

// External DNS served by R53
D("example.com", REG_NONE, DnsProvider(R53), 
    A("foo", "192.168.1.1"),
    A("bar", "192.168.1.2")
);
D_EXTEND("external_sub.example.com",
    A("xyz", "192.168.1.3")
);
```

`example.com` is deployed to BIND internally and R53 externally. Internal infrastructure uses BIND while a small amount of external infrastructure uses R53 DNS as an authoritative server for public resolving. Wildcard certificates for *.example.com obtained via `get-certs` are also deployed internally and externally.

When duplicate domain error detection was implemented in #195, it was mentioned that would be useful to add a metadata flag that permits duplicate domains.

**Comment by tlimoncelli** [comment]
I see how that could be useful. I'm not sure how easy it would be to implement.  It might "just work", or it might fail in mysterious ways elsewhere.

Would you be interested in giving it a try?   Just remove the check in `pkg/js/helpers.js` (then run "go generate") and see if it works.

**Comment by pemontto** [comment]
We're also in the same boat with a very similar use case. Have been looking for a DNS mgmt package that can handle our split-horizon DNS case.

**Comment by tlimoncelli** [comment]
I don't have much time to work on this feature, but I did a little testing and I think a volunteer will find it relatively easy to implement.

I commented out the lines in helpers.js that detect duplicate names:

```
    if (conf.domain_names.indexOf(name) !== -1) {
        throw name + ' is declared more than once';
    }
```

After that, I was able to have multiple domains. Everything seemed to work.

However, I think the code should put up some guardrails.

* There should be some way to tag each domain differently, so that the `--domains` flag can specify one or the other.  Perhaps `example.com!tag` would be the notation.
* (optional) make sure two duplicate domains have non-overlapping DNS_ destinations (optional because if someone doesn't do that, they'll get results that won't make sense and be able to correct it quickly).

The tags can be specified like:

```
D("yesthattom.com", REG_THIRDPARTY, {
        split_horizon: "1"
    },
   ...
   ...
)
```

Each duplicate domain needs to have a different split_horizon (though one can leave it out entirely).

I'm not very good at Javascript. If someone can fill in the blanks in https://github.com/StackExchange/dnscontrol/pull/1032 I'd be grateful!

**Comment by pemontto** [comment]
There may be some unexpected side effects from the first example. I think `D_EXTEND` will only extend the first domain and not all matching ones. So in the first example `xyz.external_sub.example.com` will get added to the `AXFRDDNS` entry and not `R53` which might be expected.

https://github.com/StackExchange/dnscontrol/blob/23f65163e8bb52c5b68f26f0710b3d71b8ad3a35/pkg/js/helpers.js#L127

I was about to test but got stuck trying to compile from my local repo... 😬

**Comment by tlimoncelli** [comment]
Yes _getDomainObject will have to be modified to be aware of tags too.

Alternatively it may be easier to specify the domains as `D("example.com!tag`"` so that all domains are still uniquely named. However we would then modify the Go to split it out into DomainConfig.Name and DomainConfig.HorizonTag and we'd have to handle the duplicates in Go, where it is easier to modify, test, and debug.

**Comment by tlimoncelli** [comment]
The more I think of it, the `D("example.com!tag"` is a better solution.  helpers.js is supposed to be simple and just collect data which is then validated (and otherwise processed) in the Go code. (thus, most of that PR isn't useful)

**Comment by pemontto** [comment]
Would there be a way to have one definition for common hosts in a domain, and then extending that common definition out for external/internal where they differ?

**Comment by tlimoncelli** [comment]
You could create a macro (a list of DNS records) that are common and apply the macro to both domains.

Since the language is (essentially) javascript, you could get more fancy.  For example, you could define a function BOTH(foo) that adds "foo" to both domains.

**Comment by tlimoncelli** [comment]
Good news!  Implementing this as a name, not a special meta field, makes implementing much easier and the user experience is much cleaner too. Please take a look at https://github.com/StackExchange/dnscontrol/pull/1034

With this change you can specify your domains as `example.com!inside` and `example.com!outside` and things work as expected.

Give it a try and tell me what you think!

**Comment by tlimoncelli** [comment]
FYI: https://github.com/StackExchange/dnscontrol/pull/1034 made BIND fail.  I've pushed a fix.  Please test this and let me know how it works for you.

**Comment by jasoncuriano** [comment]
I've been testing this over the last few days with a combination of the BIND, R53, and AXFRDDNS providers and haven't run into any issues. In fact it's working quite well and is by far the most elegant solution to managing split horizon DNS I've ever used. Thanks for taking the time to look at this!

**Comment by tlimoncelli** [comment]
I'm excited it's working so well!   I wish I had this when I maintained a split-horizon!

I look forward to what people build on top of this and `D_EXTEND()`.  For example, someone could make a function that takes a list of horizons and adds the same record to each of them.
