### ISSUE TITLE
HEXONET Dependency Reviewed

### ISSUE THREAD

**Issue by papakai** [StackExchange/dnscontrol#1028]
Hi @tlimoncelli 

I came now to get our dependency `github.com/hexonet/go-sdk` of the HEXONET provider module reviewed in direction of go modules and to follow best practices using vet, lint and test. 
It has now a go.mod in the repository. I guess, that this will help you guys in dnscontrol upgrades in future?
We also migrated from travis ci to github actions and to get the release process testing there, we launched a new version 3.5.1 of this module. Worked like a charm so far.

Would you mind to check if upgrading works now better for you? No worries, we have not touched the source code - just a new version.

Thanks so much!

**Comment by tlimoncelli** [comment]
Hi there!

Yes, we're fully using go.mod and the new "go modules" system.

Github actions: Hey!  We just moved to GHA too!  It's pretty impressive, IMHO.  You can see the automated tests in https://github.com/StackExchange/dnscontrol/actions (since the hexonet test creds are public, we were able to include them in the tests that run every time)

I've tried upgrading to 3.5.1 and all the tests pass: https://github.com/StackExchange/dnscontrol/pull/1029

I can merge that PR if there's nothing else to be done.  (In the future, I'll let you have the fun :) )

**Comment by papakai** [comment]
Yes, nothing else to do. Thanks man!

**Comment by papakai** [comment]
@tlimoncelli btw, no worries I am not ignoring your note about the fun you ask me to enjoy. I guess, I'll need some step by step guide on how to find back into dnscontrol development process and how to upgrade deps. I'll come back here when the time is come.

**Comment by tlimoncelli** [comment]
Cool!  Will do.

By the way... someone wrote a program that lists out the out-dated modules of a Go project. Even though its generic, I recorded my notes about using the tool at the end of https://stackexchange.github.io/dnscontrol/release-engineering (see "Tip: How to update modules").
