### ISSUE TITLE
Ignore a Zone not managed by DNSControl

### ISSUE THREAD

**Issue by jmpenalosa** [StackExchange/dnscontrol#1037]
Hi,

Is there a way for DNS Control to ignore an existing zone?

Reason is we have a common GCP Project as of the moment that utilizes the DNS service. One zone is managed through Terraform by someone else and the other zones are managed by DNS Control. Every time I run a build (Cloud Build Triggers) and it reads records that are not in `dnsconfig.js` , it deletes the said zone.

**Comment by tlimoncelli** [comment]
Hi there!

Ah, yes, that's a sticky situation.

You can use IGNORE_NAME() to tell DNSControl to not touch certain DNS labels. That way some other system can update them.  There is more info about `IGNORE_NAME` and `IGNORE_TARGET` in https://stackexchange.github.io/dnscontrol/js

I strongly suggest being cautious about using `IGNORE_*`.  The code is solid but it just feels like playing with fire. Also, the `IGNORE_*` functions aren't supported on any provider that does full zone updates each time (I think BIND and GANDI are affected).  This won't affect you now, but if you ever switch to one of those providers it may be a surprise.  This won't be a problem if you are switching between AWS/Route53, GCP/GoogleDNS, AzureDNS or any of the big players. 

Here at StackOverflow we use IGNORE_NAME() for a few specific hosts.  That said, we recently stopped using it for one domain because it was just less confusing for the humans involved (in that case, terraform now updates that zone 100%).

Tom

**Comment by jmpenalosa** [comment]
Hi Tom,

So from what I understand, this solution only ignores the records in a particular zone, correct? Not the zone itself.

My predicament is if another record is added on that "ignore.zone.com" I was talking about through Terraform, that will not have the `IGNORE_NAME()` on my `dnsconfig.js`.

So if I run it again, that new record will be deleted, correct?

**Comment by tlimoncelli** [comment]
Ah, we're talking about entire zones?  

I'm confused.  

If the zone isn't mentioned in dnsconfig.js then dnscontrol shouldn't do anything with it at all.  If it does, please file a bug.

If you want dnscontrol to manage the registrar but not the records, use the "NONE" provider.

```
var REG_GOOGLEDNS = NewRegistrar("gcloud", "GCLOUD");
var DSP_NONE = NewDnsProvider("none", "NONE");

D("example.com", 
    REG_GOOGLEDNS,   // Control the registrar
    DSP_NONE        /// Never update records
);
```

Is that what you are trying to achieve?

Maybe we should zoom out.  What problem are you trying to solve?

**Comment by jmpenalosa** [comment]
Hi Tom,

Yes, we are talking about an entire zone. 

Aha, then that zone shouldn't have been there in the first place then. I included it as I was afraid it would delete the whole zone when I push changes. I was making my own problem.

I commented the zone out, and it is working as intended. 

Apologies for the non-issue raised.

Thanks

**Comment by tlimoncelli** [comment]
No worries. Glad to see the issue resolved! (and an easy solution!)
