### ISSUE TITLE
Feature request: execute creds.json if it is executable

### ISSUE THREAD

**Issue by x70b1** [StackExchange/dnscontrol#1116]
At the moment I think its a bit hard to secure the credentials in `creds.json` as it is required to have a plaintext file.
I have seen the blackbox hint.

Ansible offers a way to run a script to retrieve the required secrets. 
Example: `vault_password_file=pass.sh` in ansible.cfg
pass.sh can now contain the vault password, or runs if it is executable. This makes it easy to integrate different solutions.

Something similar would be really cool for `dnscontrol`.

**Comment by tlimoncelli** [comment]
That's an interesting idea!

I understand the value of having a script that executes instead of reading the file.   Many open source projects use different techniques. What do you think of these?

1. The execute bit: 
    * `chmod a+x pass.sh ; dnscontrol push --creds=pass.sh`
2. Prefix with "!": 
    * `dnscontrol push --creds=!pass.sh`
3. Use a flag to indicate that creds are executable:
    * `dnscontrol push --creds=pass.sh --creds-execute`
4. Use a flag to indicate what to execute (which would override `--creds`):
    * `dnscontrol push --creds-program=pass.sh`

The first one seems unfriendly to Windows users, as the executable bit isn't used much.

They're all unfriendly to sites that need one config that works in both Windows and Linux (maybe Stack is the only place with that requirement?)

I'm interested in your feedback!

**Comment by x70b1** [comment]
Thanks for that response! I use `dnscontrol` on linux only.

I would say: All 4 ideas are solutions for the existing problem/idea.

1. Would be cool as the implementation on linux should be very easy, no bigger changes. We only have to check the file. But I have no idea ho wo solve this on windows systems.
2. Would be cool, as it is a configurable way.
3. I would be against idea as it introduces a 2nd config param that need to be set. 
4. Also nice, but introduces a new config setting too.

I would say idea 2 solves the problem without introducing a new config setting, while a solution for windows could be implemented.

**Comment by tlimoncelli** [comment]
Thanks to @jpbede and https://github.com/StackExchange/dnscontrol/pull/1119, now you can either prefix the name with `!` or set the executable bit!

Test it out and let us know how it works for ya!

Re-open this ticket if you have any problems.

**Comment by x70b1** [comment]
@tlimoncelli I checked the executable bit. It works perfekt!

@jpbede Thanks for working on it!
