### ISSUE TITLE
DS tests fail for GANDI_V5

### ISSUE THREAD

**Issue by tlimoncelli** [StackExchange/dnscontrol#1124]
DS tests for GANDI_V5 fail because the provider validates the data and our test data is just random strings, not real hashes.

Can someone that understands DS records better than me make better test data?

This is currently test 30 & 31 a.k.a. testgroup `"DS"` and `"DS (children only)"`.

CC @philpennock @kochie @jamaltebi

**Comment by philpennock** [comment]
Use something like:

```
DS	8857 8 2 4B9B6B073EDD97FEB5BC12DC4E1B32D2C6AF7AE23A293936CEB87BB10494EC44
```

That's a real value which is old (replaced with new data in May of last year) so is safe and should validate.

The first number is a uint16 which is a key tag, used to identify which key is being hashed, allowing for multiple keys.  Then there's an algorithm, a digest type, (both uint8), and finally the digest.  The algorithm matches the key in the child zone which is being hashed for use as glue here (in this case, 8 is `RSASHA256`), the digest type is the field which will determine how long the digest has to be (2 is `SHA-256`).

1. RFC 4034
2. <https://www.iana.org/assignments/dns-sec-alg-numbers/dns-sec-alg-numbers.xhtml>
3. <https://www.iana.org/assignments/ds-rr-types/ds-rr-types.xhtml>

**Comment by tlimoncelli** [comment]
Thanks, Phil!  I'll give that a try.

Do you have an example record for other hash-types too?  Particularly type 4?  I'm getting an error with:

`ds("child", 65535, 1, 4, "38b060a751ac96384cd9327eb1b1e36a21fdb71114be07434c0cc7bf63f6e1da274edebfe76f65fbd51ad2f14898b95b")),`

**Comment by philpennock** [comment]
Support for anything other than SHA-256 (and legacy support for SHA-1) is going to be limited.  A lot of providers have sanity-checks and you can only use the numbers they currently support, which is a problem when they lag behind.  Per the IANA page, SHA-384 is Optional.

Honestly for regression tests I'd stick to checking digest type `2` and limit use of the others to reporting tools rather than "fail the tests for this provider".

**Comment by tlimoncelli** [comment]
Ah!  That's what I needed to know.  That you!  Again you prove to be awesome, Phil!

Notes...

For most records with multiple fields, there are tests that change one field at a time.  This has caught bugs in both the global update algorithm and in the provider-specific code.  

In the case of DS, this might not be completely possible since changing the type also requires changes the key.  Thus, there might be fields we can't change one at a time.

I've used the example @philpennock gave and a few others I found online and was able to construct better tests. See https://github.com/StackExchange/dnscontrol/pull/1127 for the result.

**Comment by philpennock** [comment]
Minor note: RFC 4034 is the original spec, since updated.  Anything like "only this algorithm" is subject to change; the IANA links I provided above are the canonical reference to current algorithms and status ("MANDATORY" vs "OPTIONAL").
So in the comments, I'd reference that rather than perpetually claim that only SHA1 is valid (while still providing SHA2/256 testdata).

**Comment by tlimoncelli** [comment]
Updated comments in https://github.com/StackExchange/dnscontrol/pull/1134
