### ISSUE TITLE
SOA in DnsProvider not visible in generated zonefiles

### ISSUE THREAD

**Issue by flymia** [StackExchange/dnscontrol#1129]
Hi!

when trying to generate zonefiles for Bind, the SOA settings, that I make in the NewDnsProvider function are not written to the generated zonefiles.

My dnsconfig.js looks like this:

```
var test = NewDnsProvider('bind', 'BIND', {
    'default_soa': {
    'master': 'mymaster.domain.xyz.',
    'mbox': 'mymbox.domain.xyz.',
    'refresh': 10800,
    'retry': 3600,
    'expire': 604800,
    'minttl': 86400,
},
'default_ns': [
    'ns.domain.xyz.',
    'ns2.domain.xyz.',
    'ns3.domain.xyz.',
]
});


var REGISTRAR = NewRegistrar("ThirdParty", "NONE");

// Zone 1
require("domains/example-zone");
```

Now in the example-zone I have the following contents in the top:
```
D("example.domain.xyz", REGISTRAR,
	DnsProvider(test),
	DefaultTTL(172800),
```
However, when I do a dnscontrol push and look at the generated zone files, the SOA still says:

```
$TTL 172800
; generated with dnscontrol 2021-04-22T12:07:15+02:00
@          300   IN SOA   DEFAULT_NOT_SET. DEFAULT_NOT_SET. 2021042200 3600 600 604800 1440
           300   IN NS    ns.domain.xyz.
           300   IN NS    ns2.domain.xyz.
           300   IN NS    ns3.domain.xyz.

```
Do you have an idea what I am doing wrong? I'm using dnscontrol v3.7.0 and the 'preview' command nor the 'check' command shows any errors.

Thanks in advance,

Marc

**Comment by tlimoncelli** [comment]
The short answer is: Edit the zone file.

The long answer is...

SOA records are a bit weird in DNSControl.   Most providers auto-generate SOA records which can't be modified.  BIND is unique in that it requires users to manage the SOA records.  BIND's SOA support is kind of a hack.  It leaves the SOA record alone, with 2 exceptions:

1. The serial number: If something in the zone changes, the serial number is incremented.
2. Generating from scratch:  If there is no SOA record in a zone, the initial values are taken from the `default_soa` settings.  These settings are otherwise ignored.

There is an effort to make SOA records handled like A, CNAME, and other records.  See https://github.com/StackExchange/dnscontrol/pull/1115

I took your example and it worked for me.  When there was no zone, the `default_soa` values were used for the SOA record.  Now that there is an SOA record in the zone, `dnscontrol push` won't change the SOA record (other than the serial number).

**Comment by tlimoncelli** [comment]
With the SOA record handling being rewritten plus dff983131a44f34fa7c56706f5088658fff2205a I'm confident this issue is resolved.  Please feel free to re-open this issue if needed.
