### ISSUE TITLE
Support ALIAS records for Namecheap

### ISSUE THREAD

**Issue by sharat87** [StackExchange/dnscontrol#1142]
Version: `dnscontrol v3.8.1-dev`

When I have the following `dnsconfig.js`:

```javascript
var REG_NAMECHEAP = NewRegistrar("namecheap", "NAMECHEAP");
var NAMECHEAP = NewDnsProvider("namecheap", "NAMECHEAP");
D(
	"example.com",
	REG_NAMECHEAP,
	DnsProvider(NAMECHEAP),
	URL("www", "https://example.com"),
	ALIAS("@", "xyz.herokudns.com.")
);
```

I get the following error:

```
printIR.go:94: ERROR: domain httpbun.com uses ALIAS records, but DNS provider type NAMECHEAP does not support them
```

However, I am able to configure ALIAS records on Namecheap from the web UI like this:

![Screenshot 2021-05-01 at 15 13 06](https://user-images.githubusercontent.com/120119/116778491-d37a8780-aa8f-11eb-813c-afb88f7c9066.png)

I'd be interested in contributing, if this is not just implemented yet and if there's interest in considering such a PR.

Thank you for making dnscontrol :)

**Comment by tlimoncelli** [comment]
Hi there!

Yes!  PRs are always welcome!

If the web UI supports ALIAS, it should be easy to add to DNSControl.

My advice is to read the article called "Step-by-Step Guide: Adding new DNS rtypes: How to add a new DNS record type" which is on http://dnscontrol.org/   The article assumes you are starting from scratch. However since ALIAS already exists for other providers, most of that work is already done for you.  Just add what's different for Namecheap.

I'd be glad to help with any questions!

**Comment by sharat87** [comment]
Thank you for the details @tlimoncelli, turns out the change I need to make is unbelievably small. Kudos to such well-organized implementation that enabling this took such little change.

**Comment by tlimoncelli** [comment]
Merged. Thank you for taking the time to look into this and produce the PR!
