### ISSUE TITLE
Route 53 Named Profiles Fails on >3.8.0 without creds.json

### ISSUE THREAD

**Issue by biodrone** [StackExchange/dnscontrol#1261]
If running on version >3.8.0, any operation that uses creds seems to _require_ a creds.json file, whereas 3.8.0 works fine without one. This isn't made clear in the Route 53 documentation around [named profiles](https://stackexchange.github.io/dnscontrol/providers/route53), it seems like just exporting the relevant environment variables is enough.

Will submit a PR shortly with proposed clarification.

**Comment by tlimoncelli** [comment]
I'm re-opening this because it is a regression.  I'm not  in a position to be so lucky as not needing a creds.json file, but it sounds very nice to just have dnscontrol just use the creds that your AWS cli tool uses.

I don't know much about how AWS creds work but do you think you could find what changed in 3.8.0 and propose a fix?

**Comment by biodrone** [comment]
Sure can, I'll have a look shortly!

**Comment by tlimoncelli** [comment]
Is this still an issue?

**Comment by tlimoncelli** [comment]
friendly ping?

**Comment by followsound** [comment]
It has been for me in the past few weeks on `v3.31.4`

**Comment by tlimoncelli** [comment]
CC @tresni

**Comment by tlimoncelli** [comment]
This request has gone stale. Closing issue.  Please re-open if needed.
