### ISSUE TITLE
OVH: This service does not exist

### ISSUE THREAD

**Issue by 0xErnie** [StackExchange/dnscontrol#1338]
I am about to migrate a domain to OVH and want to put the configuration to code.

I created a new zone via the webinterface and can create new entries via the API, but not with dnscontrol:

> Error 404: "This service does not exist"

I am new to this tool and used to get more information easily with tools like ansible or terraform, but dnscontrol seems to be a bit clandestine, even with `-v.`

```
> dnscontrol -v preview 
******************** Domain: scrubbed.de
----- Getting nameservers from: ovh
Error 404: "This service does not exist"
```

Regarding _Since OVH doesn’t allow to host DNS for a domain that is not registered in their registrar, some dual providers scenario are not possible_: It seems like this has changed, at least for the purpose of migrating a domain to OVH.

**Comment by tlimoncelli** [comment]
CC @masterzen

**Comment by masterzen** [comment]
Hi @0xErnie,

Thanks for your report !

I believe the issue comes from the fact that we fetch the nameservers from OVH. Since the domain hasn't been transferred yet to OVH, OVH API tells us that there's no nameservers associated and returns a 404 which we interpret as an error instead of an absence of NS.
I have no idea what would happend to dnscontrol if `GetNameServers` returns an empty array, but doing so would more reflect what happens at OVH side. 
As soon as I can get some spare time, I'm going to change the code to not error on 404 and return an empty list of NS and you'll let me know if that works.

Regarding your last comment, indeed you can manage a zone while transferring a domain, but that's a bit a corner case. In a dual provider scenario, if you want to use OVH as a DNS provider, you need to register (or transfer) the domain to OVH.

**Comment by masterzen** [comment]
I've looked to this issue and indeed @0xErnie OVH does now support zones without registering a domain.
I've pushed a PR to fix the issue in the OVH provider, can you please check it fixes your issue?

Thanks !

**Comment by 0xErnie** [comment]
Thank you @masterzen, this has resolved my issue 🥳  !
