### ISSUE TITLE
Errors in New Docker Image "No help topic for"

### ISSUE THREAD

**Issue by jmpenalosa** [StackExchange/dnscontrol#1376]
This has been working for me for well over a year until today.

Here's a snippet of the GCP Cloud Build step I have:
```
- name: "stackexchange/dnscontrol"
  args: [ "/usr/local/bin/dnscontrol", "create-domains" ]
```

```
Pulling image: stackexchange/dnscontrol
Using default tag: latest
latest: Pulling from stackexchange/dnscontrol
eefa495b9cdc: Pulling fs layer
eefa495b9cdc: Verifying Checksum
eefa495b9cdc: Download complete
eefa495b9cdc: Pull complete
Digest: sha256:7e328e42842922f99cdc9a3e4971550fd78e339194a0f8a0b0f3e9558d78505a
Status: Downloaded newer image for stackexchange/dnscontrol:latest
docker.io/stackexchange/dnscontrol:latest
No help topic for '/usr/local/bin/dnscontrol'
```

I tried to change it to:
```
- name: "stackexchange/dnscontrol"
  args: [ "/dnscontrol", "create-domains" ]
```
  
I got the same error:
```
Pulling image: stackexchange/dnscontrol
Using default tag: latest
latest: Pulling from stackexchange/dnscontrol
eefa495b9cdc: Pulling fs layer
eefa495b9cdc: Verifying Checksum
eefa495b9cdc: Download complete
eefa495b9cdc: Pull complete
Digest: sha256:7e328e42842922f99cdc9a3e4971550fd78e339194a0f8a0b0f3e9558d78505a
Status: Downloaded newer image for stackexchange/dnscontrol:latest
docker.io/stackexchange/dnscontrol:latest
No help topic for '/dnscontrol'
```

Please advise if there is something I am doing wrong with the new Docker Image.

**Comment by jmpenalosa** [comment]
UPDATE:
I reverted to last known good version and it worked. It would be good to know what happened with the new image when information is available.

```
- name: "stackexchange/dnscontrol:v3.10.1"
  args: [ "/dnscontrol", "create-domains" ]
```

**Comment by tlimoncelli** [comment]
Issues with the docker builds is a known issue.  I would stick with the last known good image until we have time to fix this.

CC: @cdhunt

**Comment by mickaelalibert** [comment]
Their was a change in the last commit of the Dockerfile that modified how the image works. Now, the execution of dnscontrol is done in the ENTRYPOINT instead of the CMD of the container, which means that what was previously replaced by your `args` isn't anymore : 

- with CMD : dnscontrol you execute : /usr/local/bin/dnscontrol create-domains
- with ENTRYPOINT : /dnscontrol you execute : /dnscontrol /usr/local/bin/dnscontrol create-domains

To use the last image you need to remove "/usr/local/bin/dnscontrol" from your args.

But I now run into other issues regarding the certificates authority that aren't embed in the executable nor in docker scratch, which makes the Docker image unusable.

**Comment by aglasson** [comment]
Argg... Wish I'd checked the issues before I spent an hour and a half troubleshooting this. I thought it was an Azure DevOps issue.
I've not pegged to tag `v3.11.0` instead of letting it use latest.

How or why did a broken change even get to master without being identified and fixed or reverted? Better question, its been 10~ days? Why hasn't it been reverted? Just leave it in an entirely broken state?

**Comment by tlimoncelli** [comment]
I'm sorry that the docker image is having problems.

The process that creates it was not created by us and we can't support it.  Our plans is to adopt a new/different CI/CD tool and fix it at that time.

If you could help us by submitting a PR that would fix this it would be greatly appreciated.

**Comment by cdhunt** [comment]
Sorry, the prerelease image shouldn't have received the `latest` tag.

**Comment by cdhunt** [comment]
The incorrectly built image tags have been removed.

**Comment by viharm** [comment]
This seems like an exciting project, which I'm looking forward to learning how to configure. I'm trying to deploy this, but it appears that this problem exists in container tags v3.18.1 to v3.20.0.

The last version without this issue is v3.13.0 - over eight months & four versions old.

Is there an ETA on resolving this issue? I'm afraid I don't have the bandwidth, else I would have helped :-(

**Comment by cdhunt** [comment]
Which problem specifically, @viharm?

**Comment by saz** [comment]
@cdhunt @viharm Just guessing, but I think it's the wrong docker usage example in "Getting Started" (see https://github.com/StackExchange/dnscontrol/pull/1767 for a fix)

**Comment by viharm** [comment]
> Which problem specifically, @viharm?

I get …
```
No help topic for dnscontrol
```

**Comment by saz** [comment]
@viharm just remove `dnscontrol` from the docker command:
`docker run --rm -it -v $(pwd)/dnsconfig.js:/dns/dnsconfig.js -v $(pwd)/creds.json:/dns/creds.json stackexchange/dnscontrol preview`
