### ISSUE TITLE
hosting.de provider does not properly update nameservers

### ISSUE THREAD

**Issue by juliusrickert** [StackExchange/dnscontrol#1401]
While implementing setting default nameservers via the `providermeta` argument passed to `NewDnsProvider`, I found a bug in my implementation of the hosting.de provider.

In essence, as far as I can tell now, it never applies nameserver changes unless the `NAMESERVER` function is being called, because the nameservers present in the zone are being used instead of the default nameservers.

**Comment by maxbraeutigam** [comment]
Dear @juliusrickert, thank you very much for your provider code. I have the following (most probably related) issue:

When adding a NS entry to a subdomain (here mailings.jcf.io), the provider tries erroneously to add the NS record to the second level domain jcf.io. Furthermore, after creation it tries to create it again instead of updating it. Which ultimately leads to an error in dnscontrol.

My config:
```JS
…
NS("mailings", "ns1.sendinblue.com."),
NS("mailings", "ns2.sendinblue.com."),
…
``` 
Results in:
```BASH
CREATE NS jcf.io ns1.sendinblue.com. ttl=86400
CREATE NS jcf.io ns2.sendinblue.com. ttl=86400
FAILURE! [{Code:40010 ContextObject: ContextPath: Text:Record with name 'jcf.io', 
type 'NS' and content 'ns2.sendinblue.com' is a duplicate. Value:} 
{Code:40010 ContextObject: ContextPath: Text:Record with name 'jcf.io', 
type 'NS' and content 'ns1.sendinblue.com' is a duplicate. Value:}]
```

I am looking forward to fixing this issue. Do not hesitate to ask me to test your code.
Cheers and thank you once again,
Max

@membero

**Comment by juliusrickert** [comment]
Hi @maxbraeutigam,

you're welcome :)

Have you tested the current `master` with the fixes? Would be great to know whether there's still work to do.

**Comment by maxbraeutigam** [comment]
Hi @juliusrickert, yes, you fixed it. :-) 
But I was building against [8220257d7](https://github.com/juliusrickert/dnscontrol/commits/8220257d7284f165f1d0a73e0b60ba17e7a83a57), since neither [juliusrickert/dnscontrol](https://github.com/juliusrickert/dnscontrol/commits/master) nor [StackExchange/dnscontrol](https://github.com/StackExchange/dnscontrol/commits/master) contain your [commit](https://github.com/juliusrickert/dnscontrol/commit/8220257d7284f165f1d0a73e0b60ba17e7a83a57) fixing this issue – or do I have tomatoes on my eyes?

**Comment by juliusrickert** [comment]
> yes, you fixed it. :-)

Nice.

> or do I have tomatoes on my eyes?

You don't, I do :D

I misread Tom merging `StackExchange/dnscontrol:master` into `juliusrickert/dnscontrol:docs/hostingde-customize-nameservers`.

I thought it'd be the other way around :D
