### ISSUE TITLE
Executing of creds.json is broken but works as intended

### ISSUE THREAD

**Issue by x70b1** [StackExchange/dnscontrol#1493]
@tlimoncelli 

You put some effort into this feature. Awesome! :sunglasses: 
I found things like https://github.com/StackExchange/dnscontrol/issues/1458 and https://github.com/StackExchange/dnscontrol/pull/1456.

I used the executable creds.json feature without a `--creds` flag. This is not working anymore as you changed the logic behind it. I build dnscontrol from the master branch. `creds.json` files are now expected to be plain text json. Or in other words: The executable bit not checked for a json extension.

I guess that is intentional.

Would it make sense to search also for `creds.sh`, `creds.py` and `creds` to not have to specify the `--creds` parameter?

**Comment by tlimoncelli** [comment]
Yes, the "don't try to execute creds.json if the +x bit is set" change was due to Windows thinking all files have the +x bit set (at least in our environment. YMMV).

I think that having a file with a .json extension being executable is confusing.  It might not be technically wrong or bad, but it sure is confusing ... especially when you find yourself running "jq" on what turns out to be a shell script!

I'd like to understand the use-case better.  What do you use the executable version for?  (I'd love to hear from others that use this feature)

Tom

**Comment by tlimoncelli** [comment]
Cool. Thanks for sharing that.  

I'd love to see your script (redacted, of course) to understand how you generate the json.

**Comment by tlimoncelli** [comment]
Thank you for sharing that.   It helps me understand how people use the feature.


Thanks!
Tom
