### ISSUE TITLE
Multiple DefaultTTL With DEFAULTS

### ISSUE THREAD

**Issue by IzumiSenaSora** [StackExchange/dnscontrol#1511]
Hi i want to add different DefaultTTL per DnsProvider from DEFAULTS
at this moment i use this JSON Config

`DEFAULTS(
	DnsProvider(deSEC, 2),
	DefaultTTL(3600),
	DnsProvider(CLOUDFLARE, 2)
);`

but this JSON Config will send `DefaultTTL 3600` to `DESEC + CLOUDFLARE`
what i want to do is make `CLOUDFLATE get DefaultTTL 1` and `DESEC get DefaultTTL 3600`
is there any way to do it without touching `D(example.com)` function

**Comment by tlimoncelli** [comment]
Hi!  That's an interesting issue you've raised!

I don't think the problem is with `DEFAULTS()`.  I think what you are trying to do isn't supported by dnscontrol.  You can't supply a different TTL for different providers.

The `DEFAULTS()` function simply copies the items into future `D()` statements.  It can't do anything that couldn't be done by just manually copying items into `D()`.

Let's try to achieve the same goal without using `DEFAULTS()`:

```
D("example.com", ...
...
      DnsProvider(deSEC, 2),
      DefaultTTL(3600),
      DnsProvider(CLOUDFLARE, 2) );
...)
```

The `DefaultTTL()` statement isn't order-dependent. It is global to the entire domain.  So, this will set the default TTL to 3600 for both providers.

May I ask what you are trying to achieve by having different DNS servers with different TTLs?   I might be able to help you achieve your goal some other way.  However, I do want to point out that getting fancy with TTL values usually isn't worth it.  Cloudflare plays tricks with TTLs (https://developers.cloudflare.com/dns/manage-dns-records/reference/ttl/) and other providers cache things forever.  Thus, TTLs are more like a "suggestion" than something you can rely on down to the second.  You're not going to find much different between setting a TTL for 1 hour or 1 minute.

**Comment by IzumiSenaSora** [comment]
Hello...
What i am trying to do is
Lets say I have 50+ domain

`D("example.com", ...
...
      DnsProvider(deSEC, 2),
      DefaultTTL(3600),
      DnsProvider(CLOUDFLARE, 2) );
...)`

Doing this config looks junky
Cause i have to repeat it!...
Thats why i just used `DEFAULTS` cause thats why this feature is here ... so we dont need to repeat same thing...
Truly that not an issue... 
Issue is
I want to use TTL default value... cloudflare provide default value TTL 1 and desec TTL 3600 
I dont want to change anything.... 
But if i dont specify any TTL Cloudflare will normally set TTL 1 in all record but dnscontrol try to change desec TTL to 300 which causes error cause desec dont support less then 3600 TTL if i need less then 3600 then desec ask me to contact support for it... 
Thats the cause... that why i want 
Cloudflare default TTL value will be 1 and desec TTL value will be 3600 so i will not receive any error....

I am bad at english.... sorry if make any error

**Comment by tlimoncelli** [comment]
Hmm... DNSControl isn't made to do this.  I would set the TTL to 3600 everywhere.  Cloudflare ignores the TTL for proxied IPs (https://developers.cloudflare.com/dns/manage-dns-records/reference/ttl/).  Non-proxied IP probably don't get used very much.

You could use the CLI variables and run dnscontrol twice... once for each provider.  This is very complicated and probably isn't worth it.  It is very complex.

**Comment by IzumiSenaSora** [comment]
Ok... i am using 3600 for all provider... from the beginning ...i just wanted to know if its possible.... and it seems its not possible... anyway thanks for your time.... i will close this issue
