### ISSUE TITLE
[Feature Request] Add HTTPS/SVCB Records

### ISSUE THREAD

**Issue by IzumiSenaSora** [StackExchange/dnscontrol#1660]
[Feature Request] Add HTTPS/SVCB Records
[Here](https://ns1.com/blog/ns1-announces-support-for-svcb-and-https-records) Info About This Record Type

**Comment by tlimoncelli** [comment]
FYI: The steps to add a new record type are here: https://stackexchange.github.io/dnscontrol/adding-new-rtypes

**Comment by IzumiSenaSora** [comment]
> FYI: The steps to add a new record type are here: https://stackexchange.github.io/dnscontrol/adding-new-rtypes

I Have No Idea About Coding 😅

**Comment by IzumiSenaSora** [comment]
@tlimoncelli any news? About this request!

**Comment by tlimoncelli** [comment]
Hi Izumi,

dnscontrol is a community-driven open source project.  That means new features are added by the community; not the maintainer.

I have tagged this request "Needs volunteer" and emailed the dnscontrol-discuss email list asking for a volunteer.  

Which DNS provider do you use?  

Tom

**Comment by IzumiSenaSora** [comment]
> Which DNS provider do you use?

Cloudflare as a Main 
deSEC as a Backup

Both support HTTPS/SVCB Record!

**Comment by tlimoncelli** [comment]
CC @tresni and @D3luxee

**Comment by juliusrickert** [comment]
> FYI: The steps to add a new record type are here: https://stackexchange.github.io/dnscontrol/adding-new-rtypes

Link is outdated. Currently available at https://docs.dnscontrol.org/developer-info/adding-new-rtypes.

**Comment by christianbur** [comment]
After reading an article in c't from Heise.de, I wanted to test the HTTPS record. 
I think this record is very important because it offers many new and important functions. 

My provider already supports the record:
https://kb.inwx.com/de-de/3-nameserver/109-welche-record-typen-konnen-genutzt-werden
https://developers.cloudflare.com/api/operations/dns-records-for-a-zone-list-dns-records#Query-Parameters:~:text=any-,type,-string

The current browsers (Chrome, Edge, Firefox) also already support the HTTPS Reccord. 

Unfortunately DNScontrol is currently missing this RR, could someone please add this new record. 


Links:
https://www.heise.de/ratgeber/Wie-der-HTTPS-Eintrag-das-DNS-erweitert-und-warum-er-so-nuetzlich-ist-9658803.html
https://blog.cloudflare.com/speeding-up-https-and-http-3-negotiation-with-dns

**Comment by juliusrickert** [comment]
> This record really doesn't deserve the priority "low".

Please feel free to prioritise getting your PR in if it holds a higher priority for you.

**Comment by tlimoncelli** [comment]
FYI: I only implement that features that my employer needs.  Everything else comes from the community.

**Comment by fritterhoff** [comment]
Hello! @tlimoncelli just merged the required changes for this record types. Feel free to test and evaluate if I missed something :)

**Comment by fritterhoff** [comment]
Uff... Will check that tomorrow.

**Comment by fritterhoff** [comment]
<img width="1073" alt="image" src="https://github.com/StackExchange/dnscontrol/assets/32478819/319ddb91-9a43-4d75-b151-bfcd4c4b6c53">

**Comment by tlimoncelli** [comment]
Or maybe a bug in Clouldflare's validation code?

That said, this PR disables the tests for Cloudflare and fixes other issues: https://github.com/StackExchange/dnscontrol/pull/2926

**Comment by tlimoncelli** [comment]
I'm going to close this. The feature is shipping. Providers that don't have it can add it in their own PR.

Thanks to everyone that contributed to this!  I think this DNS records are going to be very popular!
