### ISSUE TITLE
Call for volunteer: INWX maintainer

### ISSUE THREAD

**Issue by svenpeter42** [StackExchange/dnscontrol#1668]
While going through my (much too large...) inbox I noticed that I missed quite some emails about INWX in dnscontrol. I still use INWX with dnscontrol but I don't have much time for maintaining it anymore.

I'd be happy if someone else stepped up and took over. I think @patschi might be a good candidate if he agrees.

**Comment by tlimoncelli** [comment]
Hi @patschi !    Let me tell you a little about the exciting opportunity of being a provider maintainer :-)

Actually, it's quite simple.  I'll tag you on any bugs related to the INWX provider.  About twice a year I make a big change and ask owners to confirm that I haven't broken anything.  The integration test suite is comprehensive and easy to run.

I try to make the changes as easy as possible for the maintainers... though this year I screwed that up with a big change to how TXT records are handled... which I eventually cancelled because it was going in the wrong direction.  I learned a lot from that and now am better at making changes in a way that doesn't require much action from maintainers.

The INWX provider is rather simple and there haven't been many bug reports.  The one change I'd like to make in the next 12 months is splitting GetDomainCorrections() into separate functions, but I'll do that in a way that doesn't require all providers to change at once (I learned my lesson from the TXT change mentioned above).

I'm always available to help if needed!

Tom

**Comment by patschi** [comment]
I'm happy to take over as a maintainer for INWX, yes.

The past months have been quite busy for me as well, unfortunately. So as long as the expectation is not being on-call 24/7 to instantly address things, I'm fine :D

**Comment by tlimoncelli** [comment]
Thank you, @patschi !  I appreciate it!  (and, no, I assure you its not a 24/7 oncall :-) )

**Comment by tlimoncelli** [comment]
oops... closed by mistake.

Could you send a PR with changes to OWNERS and README.md?  That's how we make it official :-)

**Comment by patschi** [comment]
PR opened with #1692. But there's nothing to adjust in README.md as far as I can see.

**Comment by killerbees19** [comment]
> But there's nothing to adjust in README.md as far as I can see.

@patschi Maybe instead in `documentation/providers.md`? 🙂

I think the mentioned file is outdated now and should be updated as well.

**Comment by patschi** [comment]
PR raised: https://github.com/StackExchange/dnscontrol/pull/2427
