### ISSUE TITLE
CLOUDFLAREAPI: Fix flakey tests

### ISSUE THREAD

**Issue by tlimoncelli** [StackExchange/dnscontrol#1711]
CC: @tresni

For some reason Cloudflare tests keep failing. It always starts at Test 34 or 39.  When I run the same tests from my workstation they're find. It's just CircleCI

https://app.circleci.com/pipelines/github/StackExchange/dnscontrol/1335/workflows/407541cf-dcf9-416e-8aea-799e1505050d/jobs/10332

**Comment by tlimoncelli** [comment]
I have a hunch that we're being rate-limited but the rate limit code in https://github.com/cloudflare/cloudflare-go/blob/master/cloudflare.go#L260 isn't working correctly.

Why would it set `respErr` without checking to see if `err != nil`?

**Comment by tlimoncelli** [comment]
Update:

Theory 1: This is a bug in cloudflare-go's retry handling.

I'm discussing this here: https://github.com/cloudflare/cloudflare-go/issues/1041

Theory 2: We're just maxing out the number of retries.

@jacobbednarz suggested that this is a badly phrased error message and we're exceeding the # of permitted retries.  The problem does go away if the number of retries is increased.   That fix is here: https://github.com/StackExchange/dnscontrol/pull/1713

**Comment by jacobbednarz** [comment]
i've updated the error message in cloudflare/cloudflare-go#1043 to make it clearer this is dying due to exhausting the number of retries. 

an alternative here is to also space out the requests a little longer to prevent them from all landing within the 5m window. not ideal but possible. hit me up if you need an account rate limit bumped to assist here.
