### ISSUE TITLE
NAMESERVER should not ignore TTL

### ISSUE THREAD

**Issue by captncraig** [StackExchange/dnscontrol#176]
As noted in https://github.com/StackExchange/dnscontrol/pull/171#issuecomment-320589164, you cannot manually set ttl for a nameserver record. You should be able to.

**Comment by ad8-bdl** [comment]
The expected behaviour is embodied in `convertzone` and the [documentation](https://stackexchange.github.io/dnscontrol/js#NAMESERVER).

e.g. `convertzone` produces NAMESERVER entries with a TTL modifier:
```
NAMESERVER('ns1.linode.com.', TTL(86400)),
```

However this raises an error with `dnscontrol`:
```
% dnscontrol preview
Executing javascript in dnsconfig.js: NAMESERVER only accepts one argument for name.
```

Removing the TTL entries seems to be an effective workaround.

**Comment by tlimoncelli** [comment]
Are there any Registrars that let you set the TTL? I don't know of any, but I'd be glad to be enlightened!

**Comment by tlimoncelli** [comment]
Closing due to age.  Please re-open if needed.

**Comment by systemcrash** [comment]
Welp, bumped into this one. Registrar treats NS records like any other. 

So when the existing records are pulled in, the diff produced always tries to modify the NS entries in `@`. ☹️ Churn and API calls. 

Anyway, `    {"ns_ttl":"3600"},` saved me.
