### ISSUE TITLE
Common IPv6 variables?

### ISSUE THREAD

**Issue by Iodun** [StackExchange/dnscontrol#1771]
On the examples doc it shows to define common IP addresses like this:
`var addrA = IP('1.2.3.4')`

I spent over half an hour looking around trying to find an example showing proper use of IPv6 addresses, but couldn't find anything.
What is the best solution for variables containing IPv6 addresses?

**Comment by IzumiSenaSora** [comment]
```
// IPv4 Var
var addrA = IP("1.2.3.4");

// IPv6 Var
var addrAAAA = "0:0:0:0:0:0:0:0";
```

**Comment by tlimoncelli** [comment]
@IzumiSenaSora is correct.  For an IPv6 address you can simply use the string as he demonstrated.

The IP() function is only needed if you plan on doing math on the IP address, which is less likely in IPv6.

**Comment by Iodun** [comment]
Thanks for your replies.
Wouldn't it make sense to have an equivalent IPv6 functionality for coherence reasons?
Or maybe a short explanation in the documentation why there is no IPv6 version of that?
I wonder if I am the only one who got confused by the lack of that.

**Comment by tlimoncelli** [comment]
Yes, the lack of symmetry is non-optimal.

Ideally IPv4 and IPv6 addresses would not even require a IP() function or even quotes!  The language should understand IP addresses as a first-class construct.   Sadly we are using a Javascript parser instead of writing our own custom parser so we have to accept what exists.

Your point is well taken.  I think there are 2 solutions here:

1. Update the docs to be clear (as suggested).

2. Rewrite IP() function to detect both kinds of addresses and do the right thing for each.  Sadly "the right thing" for v4 and v6 is very different (one is an Int, one is a String).  I think that might create more confusion than it solves.

I'll work on #1 soon.

Tom

**Comment by tlimoncelli** [comment]
PR is https://github.com/StackExchange/dnscontrol/pull/1775  

Feedback welcome!

**Comment by tlimoncelli** [comment]
PR merged. Closing issue.
