### ISSUE TITLE
Add an IGNORE() DSL directive

### ISSUE THREAD

**Issue by onlyhavecans** [StackExchange/dnscontrol#183]
Occasionally I have a record or two which is either not a supported type by dnscontrol, or I otherwise would not want it managed by dnscontrol. It would be nice to have a `IGNORE(name)` directive to allow dnscontrol to skip deleting or modifying the records

examples for why;
* DynamicDNS records controlled externally
* URL records from DNSimple & NameCheap

**Comment by tlimoncelli** [comment]
Let me make sure I understand the feature.  Basically IGNORE("label") would tell DNSControl not to touch a DNS record in that domain whose name is "label". The contents would be created by some external mechanism. (i.e. someone has inserted the record via a web UI or other mechanism)

**Comment by captncraig** [comment]
This sounds a lot like the (poorly documented) `NO_PURGE` option.

```
D("example.com", .... , NO_PURGE,
  A("foo","1.2.3.4")
)
```

Will cause dnscontrol to manage the records you define, but not delete others. Is that close to what you are asking for?

**Comment by onlyhavecans** [comment]
@tlimoncelli your summary is correct. That is the desired behavior. I'd like to define the record as being handled externally so it is not tampered with.

@captncraig that's very close, but I'd like to be able to define specific records not just a blanket behavior for all records not defined.

For now I could probably use NO_PURGE to do this but I'd still like to allow for record cleaning.

**Comment by gbrayut** [comment]
We did have something like that for the Cloudflare provider called [ignored_labels](https://github.com/StackExchange/dnscontrol/search?utf8=%E2%9C%93&q=ignored_labels&type=) but it probably is a good idea to create a better standard approach for how to do this across all providers.

**Comment by tlimoncelli** [comment]
The cleanest solution is to implement "special" records in the providers. There is now a mechanism to list capabilities of a provider (for example, some providers are marked as supporting SRV records). URL records from DNSimple & NameCheap could be implemented fairly easily as a "REDIRECT()" record that does the right thing depending on the provider.

**Comment by onlyhavecans** [comment]
At some point in the future I'd like to try my hand at adding URL record support much like the existing ALIAS records assuming someone else doesn't get to it first.

**Comment by tlimoncelli** [comment]
REDIRECT(): @onlyhavecans Nobody is currently working on it.  I did recently update the doc on how to add new record types (https://stackexchange.github.io/dnscontrol/adding-new-rtypes) so this seems like an excellent opportunity for you.

@gbrayut: Good point.  IGNORE("label") could simply generalize the code in Cloudflare's ignored_labels feature. Great idea!

**Comment by masterzen** [comment]
I've pushed PR #300 to fix this issue (and don't know why github doesn't show it).

**Comment by rblenkinsopp** [comment]
It would be great if this had support for wildcarding. ACME (Letsencrypt) DNS validation currently creates TXT "_acme-challenge.SUBDOMAIN" records for each subdomain being validated.

It would be great if I could have one entry such as:
`IGNORE("_acme-challenge*")`

Which can capture each all of these.

**Comment by masterzen** [comment]
@rblenkinsopp this is a good idea!
I'll try to produce a PR in the coming weeks (but no promise as I have very few spare time).

**Comment by captncraig** [comment]
This is something we have been mulling over for a while, but haven't pulled the trigger on yet, because of a couple of complications:

1. Some providers do not easily lend to this style of management, particularly when you need to supply the entire zone for each change. (Namecheap, gandi, bind at least are in this category.) I think this can be tested more fully by beefing up the integration tests to look for such scenarios and make sure each provider is compliant. 
2. We do have `NO_PURGE` which is kinda like this, but not as powerful. It is currently locked behind a provider-specific feature flag, but I'd like to remove that restriction once we have better testing. These features do feel "risky" to me, mostly because I'm afraid dnscontrol will start deleting things it shouldn't.

The way I think I look at things is that each record set (unique record type and name) falls into one of two caregories: managed or unmanaged. If it is managed (the default for everything), then dnscontrol will make it match your desired state, or delete it if it is not in the config.

"No purge", indicates that record sets not present in the config should be left as is (considered unmanaged) and not deleted. This is limiting because there may be certain records you do not wish to delete, but in general do want to purge unused records. If you only want to have a subset of records as "unmanaged", it can be frustrating to not be able to delete other record sets ever.

The proposed "ignore" feature will fill this gap, allowing you to say "ignore records with this pattern, but feel free to delete others if they are not in the config." This seems useful, but again, I'd like to have great test coverage before I'd really trust it.

**Comment by captncraig** [comment]
An aside about `_acme-challenge` @rblenkinsopp, what are you using to issue certs? Have you tried [dnscontrol's support for LE](https://stackexchange.github.io/dnscontrol/lets-encrypt)? 

The challenge records should be fine to delete once the validations succeed.

**Comment by rblenkinsopp** [comment]
I did realise after asking that they should probably not be there any more anyway but the request still seemed reasonable, if not for the specific case that I stated. I don't want to take this off-topic too much but I am using [traefik](https://traefik.io/) for LE support at the moment, I've not looked at dnscontrol's support for that yet.

**Comment by jeff-cook** [comment]
It looks like this may be near being released, but I'll add my use case anyway. 

I have a domain I want completely managed by DNS Control, except for one record which needs to by handled dynamically. I would really like to leave PURGE on. Thought about writing a script to update the dnsconfig.js file with the current value, just before it ran. But the IGNORE option would be best. 

Thank you for your hard work on this amazing project.

**Comment by tlimoncelli** [comment]
I noticed this issue hasn't been touched in a while.  I think that IGNORE() currently works this way. Can you verify?

**Comment by wolfedale** [comment]
I'm looking for a similar option but I would like to specify record type. Is it possible? I'm trying to use `NO_PURGE` and `IGNORE_NAME('')` but those are not doing what I'm expecting. My problem is that I want to specify some records by dnsControl, and I don't want to touch (add,modify,delete) all the others which are not in the dnsControl. 

I'm experimenting with those two but I'm always getting same result:

`
----- Getting nameservers from: gcloud
----- DNS Provider: gcloud...
1 correction
#1: CREATE A foo.example.com {MY_IP} ttl=60
MODIFY NS example.com: (ns-cloud-e4.googledomains.com. ttl=21600) -> (ns-cloud-e4.googledomains.com. ttl=300)
MODIFY NS example.com: (ns-cloud-e3.googledomains.com. ttl=21600) -> (ns-cloud-e3.googledomains.com. ttl=300)
MODIFY NS example.com: (ns-cloud-e2.googledomains.com. ttl=21600) -> (ns-cloud-e2.googledomains.com. ttl=300)
MODIFY NS example.com: (ns-cloud-e1.googledomains.com. ttl=21600) -> (ns-cloud-e1.googledomains.com. ttl=300)
`

and my config looks like this:

`
D("example.com", REG_NONE, DnsProvider(GCLOUD), NO_PURGE,
    A("foo","34.107.128.149", TTL('60')),
    IGNORE_NAME("*", "NS")
);
`

is it possible to not touch NS records?

Thanks!

**Comment by tlimoncelli** [comment]
> is it possible to not touch NS records?

Not at this time.  PRs accepted.

Please start a new issue if you want to discuss this particular situation.
