### ISSUE TITLE
Reproducibility in built BIND zones without pre-existing state

### ISSUE THREAD

**Issue by w4** [StackExchange/dnscontrol#1859]
Hi,

We do our DNS zone building in a pure environment with no existing state, this causes our builds to not be reproducible without modification to the zones, consisting of removal of comments, serial replacement, hashing, and another replacement:

```bash
# setup build directory
cp $src/* .

# build zones
mkdir zones
${pkgs.dnscontrol}/bin/dnscontrol push

# delete all the "generated with dnscontrol" lines for reproducibility
${pkgs.gnused}/bin/sed -i '/^; generated with dnscontrol/d' zones/*.zone

# replace the serial (date) in each zone with a fixed value
${pkgs.gnused}/bin/sed -i -E 's/(IN SOA[^0-9]+)[0-9]+(.*)/\1<FILEHASH>\2/' zones/*.zone

# loop over each zone (now with only reproducible data), and replace the serial
# with 32 bits of a sha256 hash of the zone
for zone in zones/*.zone
do
  HASH=$(sha256sum $zone | head -c 8)
  ${pkgs.gnused}/bin/sed -i "s/<FILEHASH>/$((16#$HASH))/" $zone
done

# move zones to output directory
mkdir -p $out
cp zones/*.zone $out
```

Is this flow something that'd be acceptable to include into dnscontrol itself behind a config flag for the provider? I'm happy to contribute it in, if so.

Thanks!

**Comment by tlimoncelli** [comment]
Hi!

Clippy says: It sounds like you're looking for more control over SOA serial number generation in the BIND provider!

Sounds like a reasonable feature request!  I would like to see it added in a generic way so that it can help many users. There are a couple ways I could see this happening: A flag that sets the serial number to be the lower 32 bits of the hash, a flag that provides a lookup table of desired SOA serial numbers, a flag that sets the serial to a constant string (which is easy to change later using `sed`), or maybe other ways to do this. I'm open to new ideas too!

Would you mind some suggestions about your process?

Using a hash as the serial number sounds problematic. Secondaries do a zone transfer when the secondary's cached serial number is lower than the primary's serial number; not when it is different.  Using a hash means sometimes a new serial number may be lower than the old number and no transfer will happen.  Do you have problems with secondaries not doing updates? 


That said...

Here are some ways this can be added:

A flag:

```
# Generate your hash:
dnscontrol preview --bind_soa_hash

# If a constant is ok...
dnscontrol preview --bindsoa=INSERT_SERIAL_HERE

# A dynamic value:
dnscontrol preview --bindsoa=$(( $(date +%Y%m%d%H%M%S) - 20221202000000 ))
# (Number of seconds since my birthday.. a value that is always increasing and will fit in 32-bits longer than I'll be alive.)
```

It could be part of creds.json:

The `creds.json` file would look like this:

```
  "bind": {
    "TYPE": "BIND",
    "directory": "$BIND_DIR",
    "constant_soa": "INSERT_SERIAL_HERE"
  },
```

If you want it to be per-domain, that's easy to do too.  Look at `pkg/js/helpers.js` for examples like `DISABLE_UNMANAGED_SAFETY_CHECK`.


Tom

**Comment by w4** [comment]
Now that you mention I did think he.net was being a bit slow lately. Suppose I better rethink my approach, I do think whatever I end up going with though (`git log --oneline | wc -l`? 😭) someone much brighter than me will find a good use for this.

Also, happy belated birthday :)

**Comment by tlimoncelli** [comment]
In that case, a flag like `--bindsoa=INSERT_SERIAL_HERE` (or maybe `--bindserial` is a better name?) would be the most generic.  It is generic enough that it can be used with a string for later `sed`ing or a value if you want to set a specific integer.

I appreciate the value of 100% reproducible builds.  However the serial number definitely makes that a challenge.

On the other hand, if you are using he.net, have you considered using the HEDNS provider and then you can be the secondary?

Or, you can have dnscontrol generate both a BIND zonefile and send it to HEDNS via the api:

```
var DSP_HEDNS = NewDnsProvider("hedns");
var DSP_BIND = NewDnsProvider("bind");
D("example.com", REG_WHATEVER,
    DnsProvider(DSP_HEDNS),
    DnsProvider(DSP_BIND),
    ...
)
```

**Comment by tlimoncelli** [comment]
any news here?
