### ISSUE TITLE
cannot set ttl to 1 minute with cloudflare

### ISSUE THREAD

**Issue by andrewvmail** [StackExchange/dnscontrol#1952]
```
A('metabase', '123.123.123.123', TTL('60s')),
```
this statement turn into this in preview
```
#1: MODIFY A metabase.helloworld.com: (123.123.123.123 ttl=1 proxy=false) -> (123.123.123.123 ttl=120 proxy=false)
```

tried also 

```

A('metabase', '123.123.123.123', TTL('60')),
A('metabase', '123.123.123.123', TTL(60)),
A('metabase', '123.123.123.123', TTL('1min')),

```
all valid but does not give ttl=60

also went back download releases up to august last year same thing

**Comment by tlimoncelli** [comment]
The cloudflare provider code enforces a minimum 2 minute TTL.

This was done because the Cloudflare API increases the TTL to 120 if you set it to anything lower.  Without DNSControl also enforcing the 120 minimum, the updates failed as the client and server battled each other.  (That code was written many years ago)

**Comment by andrewvmail** [comment]
I think they might have changed since then.
The current docs at https://developers.cloudflare.com/dns/manage-dns-records/reference/ttl/#unproxied-records

Says
<img width="765" alt="image" src="https://user-images.githubusercontent.com/2431354/214992297-c145a4e9-b9af-45a6-b2cb-d64fdd53959c.png">

I did a PR and tested it using that build and it worked fine.

**Comment by tlimoncelli** [comment]
PR approved. Thanks for not just finding the problem, but providing a PR to fix it!  This is how community-run projects should be!
