### ISSUE TITLE
HOSTINGDE: SOA Support

### ISSUE THREAD

**Issue by Yannik** [StackExchange/dnscontrol#1972]
The `HOSTINGDE` API does support setting custom SOA records for zones, however this needs to be done in the `ZoneConfig` and not as a regular record.

Currently, this is not implemented within dnscontrol. I'm creating this issue to track this feature.

@juliusrickert @membero Would you be interested in adding this?

**Comment by tlimoncelli** [comment]
What problem are you having that would be fixed by being able to update the SOA record?

**Comment by juliusrickert** [comment]
@tlimoncelli I think it's just about managing SOA records, like changing them to include the primary nameserver or the administrator's email address.

IIRC it wasn't supported by DNSControl when I initially wrote the hosting.de provider.

**Comment by tlimoncelli** [comment]
I have no problem with implementing SOA records in a provider.  If you have the time and inclination, please do so.  I'll gladly accept the PR.

However.... I think your time is best spent on other features.   Time is precious.  Be careful how you use it. [(Shameless plug.)](https://www.tomontime.com/)

Why?

Yes, the RFCs say that those fields should be populated with the primary nameserver and admins email address. However I know of zero systems that actually use that data today.   Secondaries transfer from all NS's or use a hardcoded IP; "whois" is more accurate for the admin address.

Frequently people want to implement SOA records for completeness or just "because we can".  However that adds code that has to be maintained, tested, etc. That's not a good reason to add code to a project.

Maybe there's a business reason to add SOA report.  For example, maybe someone has a billing system that uses the admin field.  If someone comes forward with such a reason, I'd fully support using time to write this feature. However I don't think anyone is going to come forward with such a request.  My recommendation is to close this ticket and re-open it if anyone does come forward.

**Comment by juliusrickert** [comment]
> I think your time is best spent on other features

That's probably true. More like a perfectionist's treat :D

> [(Shameless plug.)](https://www.tomontime.com/)

P.S. Squarespace is giving me a 503 for anything but the index page.

**Comment by tlimoncelli** [comment]
Agreed.  

I'm going to close this issue.

**Comment by Yannik** [comment]
Hi Tom and Julius,

> What problem are you having that would be fixed by being able to update the SOA record?

Thanks for asking this question!

> Frequently people want to implement SOA records for completeness or just "because we can". However that adds code that has to be maintained, tested, etc. That's not a good reason to add code to a project.

You are right, and I also agree that most of the SOA fields do not serve a purpose these days.

However, there is one field that is used all the time and which I usually like to configure: the negative caching ttl.

Best regards
Yannik

P.S.: It would be nice to wait for feedback to your questions before closing issues :D

**Comment by tlimoncelli** [comment]
(I apologize for the premature close. That was inappropriate and I'll be careful not to do it in the future.)

Ah!  Yes, the negative caching ttl is used.

**Comment by Yannik** [comment]
Thank you, Tom :) I appreciate it.
