### ISSUE TITLE
NS1: ` ERROR: provider code already removed nameserver trailing dot`

### ISSUE THREAD

**Issue by norman-zon** [StackExchange/dnscontrol#2254]
This is a follow up to https://github.com/StackExchange/dnscontrol/pull/2217.
I just noticed (v3.30.0), when **creating a new zone** I get `ERROR: provider code already removed nameserver trailing dot` now.

`push` and `preview` for an existing zone works as expected.

Tried to look into it, but I'm really not good with Go.

EDIT:

I investigated further and the zone indeed gets created with a `NS` record that has the trailing dots stripped. But every consecutive run fails again with the above error message.
Manually adding the trailing dots in the NS1 WebUI makes it work again.

**Comment by norman-zon** [comment]
CC @costasd

**Comment by costasd** [comment]
Hmmm, will check today! Thanks for the report!

**Comment by costasd** [comment]
So, it was way more confusing from what I initially thought, hence the delay here. I started looking into our full pipeline, being convinced the dots we're stripping are actually not being added back due to some bug on our side. The explanation though is way simpler than that...

It seems that NS1's API may return trailing-dotted nameservers on newly created domains but may also return nameservers without dots.

What I mean by that:
While testing 3 different domain creations/deletions via the rest API, across 2 accounts, to my surprise, I saw:
* Two got assigned nameservers **without** trailing dots on creation (=old behavior).
* One got assigned nameservers **with** trailing dots (=new behavior that Norman fixed in #2217).

And if it's not mind-bogling enough, all domains when queried via dig, seem to return trailing-dotted nameservers as they should be expected to, regardless of what the API or the UI says!

The only possible explanation I can think of, is that they haven't finished deploying the new code that ensures API agrees to DNS across their API backends, and I'm hitting different backends for different domain creations...

Coming to the issue now - if we end up with a newly-created domain that gets assigned non-dotted nameservers, `models.ToNameserversStripTD()` will error out, 'cause it can't find trailing dots. The reverse issue from what was fixed in #2217 basically!

I'll reach out to them, but for now I'm testing more and preparing a workaround PR to cover this behavior on dnscontrol's side - which will stop these ERRORs from manifesting.

**Comment by norman-zon** [comment]
Thanks a lot for the thorough investigation and the workaround, @costasd!
It really is a pity NS1 don't version their API and publish release notes for it.
I hope they will answer your inquiry and fix it on their end for good.

**Comment by costasd** [comment]
OK, after some rest and more tests, I get to a somewhat different conclusion. Not that inconsistent as I originally thought, but still inconsistent in a different way:

1. NS1's API nowadays (since Norman's discovery in #2217) returns whatever you store to it as nameservers - dotted or not dotted.
2. Before the change,  NS1 was returning not dotted, regardless of what you stored  - so `models.ToNameservers()` worked.
3. dnscontrol is opinionated and always pushes dotted nameservers - as it should.
4.  new zones get assigned and return nameservers without dots in API and UI - breaking what #2217  fixes.
5. all zones have dotted nameservers when queried  through DNS (e.g. with dig or drill) regardless of what the UI/API says.

So the bug is:
* In case of new zones (case 4) -> no dotted servers -> we need `models.ToNameservers()`
* In case of existing zones (case 1+3) -> could be dotted or not dotted, depending what we stored -> brokenness because we need both `models.ToNameservers()` and `models.ToNameserversStripTD()`

I'll update the commit message to reflect the issue correctly.
