### ISSUE TITLE
Comparing with octoDNS

### ISSUE THREAD

**Issue by dlemenkov** [StackExchange/dnscontrol#2310]
Hi! I found this project really helpful. There are extremely few alternatives to DNSControl in DNS management problem. So.. alternatives -- is what my question about. I am wondering if there is a fundamental difference between DNSControl and octoDNS.

At the first look, both of them look similar in a general way:
* implement Infrastructure-as-code approach in DNS provisioning;
* support 30+ main DNS providers;
* have a nice CLI;
* have a 5-year success story;
* have a community support and are used by a remarkable company.

At the second look, there are few differences:
* JS-based DSL (DNSControl) vs. YAML (octoDNS) as a configuration language;
* Go (DNSControl) vs. Python (octoDNS) as a core programming language;
* respectively binary vs. source-code distribution format;
* monolithic (DSNControl) vs. modular (octoDNS) architecture (regarding DNS providers).

However, all of these differences seem to be minor and insignificant for end user.

Is there any difference in a strategy vision or in fundamental functionality that I missed?
Would really appreciate your thoughts on this.

P. S. I understand that it's not an ordinary issue format, so feel free to close it at any time :)

**Comment by tlimoncelli** [comment]
You might get more feedback if you discuss this on the <dnscontrol-discuss@googlegroups.com> email list.

But here's my opinion...

I evaluated OctoDNS a few years ago and think it is quite nice.

I think the biggest difference is the language.  OctoDNS uses YAML, which is simple to parse and understand.   DNSControl uses a Javascript interpreter to enable loops, macros, and so on.  (YAML has [anchors and references](https://stackoverflow.com/questions/46641224/what-is-and-in-yaml-mean) but they're not nearly as useful.

The DNSControl language lets you set up [macros](https://docs.dnscontrol.org/advanced-features/code-tricks) so that you don't have to repeat yourself.  It has [builders](https://docs.dnscontrol.org/language-reference/record-modifiers/dmarc_builder).

My goal in creating DNSControl is to enable the engineers at my company, who don't know a lot about DNS, to send a PR without having to learn much about DNS.  OctoDNS's language seems to require more DNS knowledge.

DNSControl used to include tools for importing and exporting OctoDNS config files.  There was a provider that output OctoDNS config files... in theory if OctoDNS supported a DNS provider that DNSControl didn't support, you could generate the OctoDNS config and let OctoDNS do the hard work.  I don't think anyone used any of the OctoDNS support in DNSControl, and so they were removed last year.  I think nobody used them because once you are using either tool, you're probably not going to switch.  Those that do switch will probably use `dnscontrol get-zones --format=js` which has the benefit of going directly to the DNS provider, removing OctoDNS as the middleman. 

Which is better?  I don't think you can go wrong with either.  Any kind of DNS-as-code is better than click-click-click-clicking on control panels at your DNS provider.

Tom

**Comment by tlimoncelli** [comment]
Ok to close this issue?

**Comment by dlemenkov** [comment]
Really thanks for your explanation!
Will try to stay with DNSControl :)

**Comment by sosnik** [comment]
To answer OP's question, I think the fundamental difference between octoDNS and DnsControl is not the architecture nor the form, but, rather, the function. OctoDNS *syncs between providers* while dnscontrol *pushes a single source of truth to multiple providers*.

With OctoDNS it is perfectly possible to ignore the YAML configuration and merely sync an existing BIND source to third-party DNS providers. Something I would argue is ideal if you want to configure dual DNS without changing your existing setup too much. You'll continue to write zonefines in BIND, and those zonefiles will be synced to R53, GCP, Azure, OCI and et cetera.

You cannot really do that with DnsControl. You need to migrate from your current provider (in my case: BIND) and sync outward. 

A difference in DnsControl's favour is that the language is much less verbose compared to octoDNS. If you want to configure SRV or MX records in octoDNS YAML, you need to explicitly use all of the field names — in my case, I am used to editing BIND directly, so I remember the order of values, but not the field names.

The second, obvious, factor in favour of DnsControl is the ability to create macros and transforms. Doing this is clunky with OctoDNS and impossible in plain BIND (where you need to write an external script to 'fake' ALIAS records).
