### ISSUE TITLE
MacPorts included in install instructions, but not maintained?

### ISSUE THREAD

**Issue by mejofi** [StackExchange/dnscontrol#3021]
It looks like there is currently no maintainer for the MacPorts package, putting the latest available version at 4.3.0;

https://ports.macports.org/port/dnscontrol/details/

**Comment by cafferata** [comment]
Hi @mejofi, 👋🏻

Thank you for bringing this issue to our attention. You saw that well. The current DNSControl releaser ([GoReleaser](https://goreleaser.com)) does not have the option to publish to MacPorts, similar to [GoReleaser: Homebrew](https://goreleaser.com/customization/homebrew/). And it looks like there will be no MacPorts support either. See https://github.com/goreleaser/goreleaser/issues/1556

In addition the timeline:
* [Aug 8, 2022](https://github.com/macports/macports-ports/pull/15657#discussion_r940182657) Introduction of the MacPorts, including coordination of maintainer role with @tlimoncelli.
* [Aug 26, 2022](https://github.com/StackExchange/dnscontrol/pull/1729) Added to the README. See https://github.com/StackExchange/dnscontrol/pull/1729
* [Aug 24, 2023](https://github.com/macports/macports-ports/pull/20108#issue-1865276373) @ajhall has retired as a maintainer. See https://github.com/macports/macports-ports/pull/20108

@tlimoncelli I suggest we remove the old references from our GitHub repository and do the same on the side of [macports/macports-ports: sysutils/dnscontrol/Portfile](https://github.com/macports/macports-ports/commits/master/sysutils/dnscontrol/Portfile). 

**Two questions**
1. What do you think about it? See https://github.com/StackExchange/dnscontrol/pull/3022.
2. Shall I prepare the GitHub pull requests [macports/macports-ports](https://github.com/macports/macports-ports)?

**Comment by tlimoncelli** [comment]
I concur.  We should remove support for MacPorts if we can't maintain it and/or automate it.

I'll review and merge https://github.com/StackExchange/dnscontrol/pull/3022 soon.

**Comment by pmetzger** [comment]
This is crazy. There is no problem updating MacPorts. Why did you say we can't?

**Comment by tlimoncelli** [comment]
Hi Perry!  I didn't know you use dnscontrol!  What a surprise!  Are you still in the NY area?

The current version is 4.12.0.  MacPorts is stuck on version DNSControl version 4.3.0 (Aug 2023).  

I'd be glad to revert https://github.com/StackExchange/dnscontrol/pull/3022 if someone gets it unstuck.

However I'm going to put some conditions on this:

1.  For this project to support MacPorts in the future, a volunteer has to step up to support it.
2. MacPorts support has to be part of our automated CD process (or happen outside of it).  It can't add manual work to the release process.

Otherwise, macOS users can continue to install DNSControl via Homebrew, source, or use the Docker images.

**Comment by pmetzger** [comment]
I don't really see why it's of importance that your release process be connected to maintenance in MacPorts; MacPorts maintains its own CI infrastructure. Regardless, people don't use Brew and MacPorts at the same time, so if someone uses MacPorts, they're not going to be using Brew.

**Comment by pmetzger** [comment]
(BTW, it's routine that there is no maintainer for a particular port in MacPorts; when that's the case, people just do collective maintenance. A maintainer is someone who "owns" the port and gets say over changes to the Portfile etc.; many ports have no specific maintainer.)

**Comment by pmetzger** [comment]
FYI, a trivial bump in the version number (and update of the checksums) in the Portfile seems to have been sufficient to update the port. It took me all of five minutes.

**Comment by cafferata** [comment]
@pmetzger, I think it's completely fine if you want to manually update MacPorts yourself. @tlimoncelli and I will not do that for the [DNSControl MacPort](https://ports.macports.org/port/dnscontrol/details/).

P.S. In the meantime, between [your change](https://github.com/macports/macports-ports/commit/96971d0b482b6c6c4263b8b5d1b7df3544080e41) and the DNSControl release [v4.12.1](https://github.com/StackExchange/dnscontrol/releases/tag/v4.12.1), there is again a need to update the [DNSControl MacPort](https://ports.macports.org/port/dnscontrol/details/). This shows that a DNSControl MacPort maintainer is necessary in the longer term.

In addition, I want to prevent our DNSControl users such as @mejofi from running into an very old DNSControl version: [v4.3.0](https://github.com/StackExchange/dnscontrol/releases/tag/v4.3.0) (_almost 1 year ago_). This is not the user experience we want to provide. That's why we decided to remove MacPorts from the installation method. https://github.com/StackExchange/dnscontrol/pull/3022

In addition, I noticed that [the build is failing](https://build.macports.org/builders/ports-10.8_x86_64-builder/builds/183599), what would you expect? Who's job would it be to fix this MacPort build? This also shows that a DNSControl MacPort maintainer is necessary in the longer term.

Anyway, i'm closing this GitHub issue. The [stated conditions](https://github.com/StackExchange/dnscontrol/issues/3021#issuecomment-2200921045) are not guaranteed. Feel free to create a new issue showing that the MacPorts versions will continue to be updated and reintroducing the MacPorts installation.

**Comment by pmetzger** [comment]
> This shows that a DNSControl MacPort maintainer is necessary in the longer term.

Not having an assigned single maintainer doesn't mean that there's no maintenance of a port, it means there's no _maintainer_, meaning no one with veto power over how a port is managed. You could have gotten us to pay more attention by filing a single ticket.

We don't need to add a maintainer; all that would do for a Portfile with almost no machinery in it is add three days of latency before someone does their own update because we would have to wait for the maintainer to have an opinion which they probably wouldn't. Having a person listed on the maintainer line doesn't necessarily mean a port is up to date anyway; we have almost 20,000 software packages in the collection, and things sometimes get lost in the cracks.

Also, if you're going to be really insistent that you aren't going to change how you run your project based on my comments, it's hypocritical to tell us that we "need" to do something based on your comments. 

Regardless, filing a pull request, as you did, telling us to remove the port was unreasonable. You could have just as easily changed the three lines (literally three) in the Portfile to bring it up to date and have it compile. If you believe that the current update is critical, file a pull request asking for the update; if the CI passes I will merge it immediately. You can even automate that in about five minutes.

**Comment by pmetzger** [comment]
BTW, if one of you wants to volunteer, you can add yourself as "maintainer". That means that your pull requests will be (almost) always merged immediately. I don't think it's necessary but if it's important to you, feel free.

**Comment by tlimoncelli** [comment]
> A trivial bump in the version number (and update of the checksums) in the Portfile seems to have been sufficient to update the port. It took me all of five minutes.

Perry, you've been in tech for long enough to know that that's not a valid argument.  You're comparing the time it takes someone with years (decades?) of MacPorts experience to the level of effort required by someone with very little experience.  I won't stand for bad-faith arguments like that.

The fact that you could have fixed it, but chose not to... smh.

Perry, I think we first met in ... 1985-ish?   You know better and can do better.

I'm leaving this issue closed.  MacPorts is like any unaffiliated project that decides to independently package up DNSControl and make it available.  We appreciate their effort and will gladly answer questions, etc, but we have no obligation to advertise it in our README.md.

You've exhausted the amount of time I'm willing to spend on this. We're a small project with limited resources.

Thank you for fixing the current problem.  I wish MacPorts great success and mean no ill.

**Comment by pmetzger** [comment]
>I've shown good intentions by removing an outdated MacPort. You clearly indicated that this was not desired. The pull request is closed and as far as I'm concerned so is this discussion.

That was not a reasonable request. Nothing was outdated. Nothing was failing about the build. Well intentioned would have been filing a ticket asking the port be updated.

> I'm leaving this issue closed.

I don't care. Mention that we have the port, or don't. Not my business. But I would prefer that people working on dnscontrol not file future requests to remove the port from MacPorts on the basis that they think something is "unmaintained" or don't like how we run MacPorts.

**Comment by pmetzger** [comment]
> You've exhausted the amount of time I'm willing to spend on this. We're a small project with limited resources.

You're hardly alone in that. Just understand how this looked: someone from your project arrived, informed us that we weren't maintaining something because they don't understand our process, requested that we remove a perfectly good Portfile from our repository on the basis that we aren't maintaining it because we didn't have a named maintainer, and other people start lecturing me how the thing is broken because our buildbots aren't successfully creating binaries for a 12 year old version of MacOS. It ain't a good look.

If someone is irritable that our version is out of date, tell them to file a ticket. We'll update it.

**Comment by pmetzger** [comment]
Oh, and it's not my business if you list us in your "how to get this" or not. I just don't want more people arriving and filing tickets to remove the software from MacPorts because you don't like that we don't have a named maintainer. We have 20,000 software packages with Portfiles and not all of them are going to have a named person responsible.
