### ISSUE TITLE
GCLOUD: Errors creating Domains starting with a number

### ISSUE THREAD

**Issue by AndreasSaeckl** [StackExchange/dnscontrol#332]
Hi!

we registered a new domain starting with a number. We're getting following error when we're executing "create-domains":
Adding zone for 50-domain123.com to gcloud account
Error creating domain: googleapi: Error 400: Invalid value for 'entity.managedZone.name': '50-domain123-com', invalid

Google Troubleshooting: https://cloud.google.com/dns/troubleshooting?hl=en
"The managed zone creation operation can fail with this error if the managed zone name does not begin with a letter, end with a letter or digit, and contain only lowercase letters, digits, or dashes."

Can you fix this issue? Thanks!

Greetings
Andreas

**Comment by captncraig** [comment]
At first look I was thinking this was purely on Google's end, but I guess this is the zone "name" field that doesn't really matter except for how it shows in the management console. We use the domain name, because that seems like the best choice. I think its silly that there is even a distinction.

So there are a couple of options:

1. You can manually create that zone in the web console, and it should work from there. 
2. We can detect invalid names in [the code](https://github.com/StackExchange/dnscontrol/blob/master/providers/gcloud/gcloudProvider.go#L236), and add some prefix. I'm really not sure what the best choice would be. Feels silly to prefix "a" for no good reason. Maybe "dnscontrol-"domainname or something?

**Comment by AndreasSaeckl** [comment]
I think Option 2 would be the best solution for this with prefix "dnscontrol-"domainname.
Others will get this problem as well in the future and it would be nice to not having this limitation ;-)

**Comment by tlimoncelli** [comment]
I opted for "zone-" because it is shorter and the description already has "dnscontrol" in it.

https://github.com/StackExchange/dnscontrol/commit/2579336cdba2e3fcd9e859dd9cf6cef5521125c6

Let me know if that works.

**Comment by AndreasSaeckl** [comment]
Works perfectly, thank you!
