### ISSUE TITLE
Digitalocean TXTMulti support

### ISSUE THREAD

**Issue by Deraen** [StackExchange/dnscontrol#370]
Hi,

I'm looking into adding TXTMutli support to Digitalocean provider. This would be matter of just adding the flag except for one test case:

```
			tc("Create TXTMulti with quotes",
				txtmulti("foo1", []string{"simple"}),
				txtmulti("foo2", []string{"o\"ne", "tw\"o"}),
				txtmulti("foo3", []string{"eh", "bee", "cee"}),
			),
```

While Digitalocean supports multiple values with TXT records, using escaped quotes is not allowed. This wouldn't work with DO even without TXTMulti so maybe this test case should be disabled or something?

**Comment by tlimoncelli** [comment]
Awesome!  Hopefully they have good news.

**Comment by tlimoncelli** [comment]
@Deraen Is this ready to be closed?

**Comment by Deraen** [comment]
@tlimoncelli The same problem about escaped quotes still exists. But similar to what I did with CAA support, I could add support for TXTMulti and modify the test case for Digitalocean, to skip the problematic value.

I see now that the provider feature matrix can also contain comments about supported features, so I could add those for CAA and this feature.

**Comment by tlimoncelli** [comment]
I'm trying to limit the number of special cases for providers.  We want to avoid the the surprises when changing providers.  One of the promises of dnscontrol is that you can change DNS providers easily.  I'd hate to put users in a situation where they had a zone at one provider for years, then move to a new provider only to find that their zone can't move.  That's a nasty surprise.

One way to handle this is that the validation code (`pkg/normalize/validate.go`) could print a warning if there is a quote (something like: Warning: quotes may not work for all providers).  At least that prevents a surprise.

In that case, it should list a URL of a doc that gives more details, including a the ticket id number from the provider's customer support system.  This isn't to shame the provider, but to help someone that might want to get it fixed by giving them an ticket they can point to to show the provider that this has been an issue for a long time. (and... it shames the provider :-) )

Additionally maybe (I just thought of this... it may be half-baked) we should require the user to sign off on such a situation.  Like... the warning goes away if they add "{permit_quotes_in_caa:"true"}" to the record.  That way they've acknowledged the trouble they may find themselves into some day.

**Comment by Deraen** [comment]
I just found out the repository Digitalocean uses for [API issues](https://github.com/digitalocean/api-v2/issues) yesterday, so I'll be creating issues there.

Users already can have zone work for years, and then try to move to another without support for some features and it will also stop working. But I guess the validation for these cases where feature is supported but certain cases of don't work could be better.

Would it be enough tho show the validation warning if a record has known bad config with the used provider? It could then show better warning than just returning whatever error the provider API throws.

And an idea, what about adding Partial capability? Digitalocean provider could mark CAA and TXTMulti support as partial. By default the features wouldn't be enabled, but if user needed these features, one could check the documentation for way to enable these (cli flag or something) after reading the notes about what is missing.

**Comment by tlimoncelli** [comment]
Yeah, those are all good ideas.  Its a trade-off between complexity and need.  I don't want to add a lot of complexity just because of one provider.

For example, we could have each provider include a function that scans a zone and turns a list of warnings.  However that feels like we're encouraging/enabling providers to be broken.

I'd rather have the full capability or none at all.  Anything partial is a whole lot of complexity and (more importantly) creates uncertainty for the user.  Ideally dnscontrol is set up by someone that knows DNS well, but enables PRs from their coworkers that aren't as knowledgeable.

Right now I'm fine with having `pkg/normalize/validate.go` warn people.  We can improve in the future.

**Comment by tlimoncelli** [comment]
Hi @Deraen !

I've decided to move forward with this.  https://github.com/StackExchange/dnscontrol/pull/949 enables TXTMulti for Digital Ocean.  The feature matrix includes caveats. The integration tests skip D.O. for certain features.  Please take a look.

**Comment by tlimoncelli** [comment]
Fixed by https://github.com/StackExchange/dnscontrol/pull/949
