### ISSUE TITLE
Route53 DelegationSet Support

### ISSUE THREAD

**Issue by loosi** [StackExchange/dnscontrol#397]
It would be great to set a DelegationSet (or/and maybe create one) for Route53. I see a few pieces of error handling stuff for delegationSets, but no metadata for Route53 at all. 

I'll have a look how to inplement that feature, but Go aint my favourite language...could take a  while

**Comment by loosi** [comment]
Its a convenience only feature for  registrars without real api. For example: our registrar hetzner does provide an "api"...based on signed mail. Thats not usuable for tools like dnscontrol. I fixed this situation by myself with different shell scripts. 

Its not really important, but could mean easier work for some people with different registrars.

**Comment by rileyberton** [comment]
Adding my support for this concept.  Some registrars don't even have API support.. providing them with a finite delegation set to work with is much preferred over oodles of random sets.

**Comment by tlimoncelli** [comment]
Sounds like a perfectly reasonable feature to add to dnscontrol.  I think this kind of feature is best implemented by someone that needs the feature, because they best know what workflow/syntax/etc. would work best.

That said, it isn't a feature that StackOverflow requires at this time therefore we'd appreciate a PR from someone in the community.  Otherwise we'd just be guessing at what people need.

Feel free to brainstorm here about syntax, etc.

**Comment by rileyberton** [comment]
I took a crack at this. 

https://github.com/StackExchange/dnscontrol/pull/448

This works for ROUTE53 and GCLOUD if the delegation sets and name server sets are already created.  It only applies on `create-domains` and is not yet supported on `push` (moving zones to different delegation sets, e.g.).  

I also added support for Route53 retries which I ran into while processing ~3000 zones.

**Comment by rileyberton** [comment]
This is now supported with the merge of #448

**Comment by tlimoncelli** [comment]
Fixed by #448
