### ISSUE TITLE
TXT records should check length at compile time

### ISSUE THREAD

**Issue by tlimoncelli** [StackExchange/dnscontrol#418]
Substrings in TXT records may not be longer than 255 bytes.  This should be checked at compile time (pkg/normalize/validate.go) instead of waiting to be rejected when the API rejects it.

**Comment by jasonbcox** [comment]
+1 for this issue. I found out today that GANDI_V5 will silently accept TXT records longer than 255 bytes, but will fix it for you. Consequent `dnscontrol preview` will indicate that the records do not match, so it will attempt an update every time.

#680 is related since GANDI_V5 support for multi-TXT records will be broken if this issue is fixed before a patch like this is applied.

**Comment by jasonbcox** [comment]
Gandi will silently split the string. Sorry for not clarifying. IMO truncating it would be broken :)

**Comment by tlimoncelli** [comment]
(at the risk of restating the obvious)

The goal would be to error out at compile time so that the user can substitute multiple smaller strings.  We won't have to care if the API splits strings or not if we never send it strings that are 255 octets.

**Comment by tlimoncelli** [comment]
Hey folks!

This was more complicated to implement than expected. I decided that helpers.js should just record intentions and let the Go code to all the work. (This is generally how things are done anyway.)  The normalization/validation required moving things around.

Please download https://github.com/StackExchange/dnscontrol/pull/947 and run  "dnscontrol preview" on your existing configs to make sure nothing changes.
