### ISSUE TITLE
Warning underscore in entries

### ISSUE THREAD

**Issue by pierrehenrymuller** [StackExchange/dnscontrol#452]
Hi,
Why dnscontrol put warnings on fqdn contains underscore?

RFC tell that's permitted and we got messages like that in preview or push command

>     WARNING: label _jabber._tcp.domain.com contains an underscore
>     WARNING: label _sip._udp.domain.com contains an underscore
>     WARNING: label _xmpp-client._tcp.domain.com contains an underscore
>     WARNING: label _xmpp-server._tcp.domain.com contains an underscore

Can we have an option to remove this warning?
Thanks

**Comment by tlimoncelli** [comment]
Part of being an [an opinionated system](https://stackexchange.github.io/dnscontrol/opinions), we warn about things that are above and beyond what the RFCs require.  To that end, we warn about underscores in hostnames because it usually isn't what was intended. That said, we do a have a list of exceptions.  I'll add the above items to pkg/normalize/validate.go

https://github.com/StackExchange/dnscontrol/pull/453

**Comment by pierrehenrymuller** [comment]
ok thanks

**Comment by tlimoncelli** [comment]
I've added those hostnames to the exception list: https://github.com/StackExchange/dnscontrol/pull/453

**Comment by karolkania** [comment]
That's a great idea actually, although it'd be great to let everyone specify some meta option to skip the warning message for selected records - similar solution is already in place for `skip_fqdn_check`:
https://github.com/StackExchange/dnscontrol/blob/master/pkg/normalize/validate.go#L114-L116

@tlimoncelli

**Comment by tlimoncelli** [comment]
Yes and no.  We'd rather have an opinionated feature than a configuration option that requires testing and maintenance.  I haven't heard many complaints about underscores.  I'd accept a PR if you feel strongly about it.
