### ISSUE TITLE
OVH: Modifying DKIM records fails

### ISSUE THREAD

**Issue by patschi** [StackExchange/dnscontrol#483]
I've come across a bug when dnscontrol tries modifying an existing DKIM entry via OVH, which fails with the error shown below:
```
#2: MODIFY TXT dkim._domainkey.domain.tld: ("v=DKIM1; k=rsa; t=s; s=email; p=[DKIM]" ttl=900) -> ("v=DKIM1; k=rsa; t=s; s=email; p=[DKIM]" ttl=1800)
FAILURE! Unexpected HTTP return code (400 Bad Request : {"message":"Try to alter read-only properties: fieldType"}).
```

Creating and deleting such records (with the same DKIM, etc) works just fine, just modify is broken. Unfortunately I'm not sure what might causing this... any thoughts?

**Comment by patschi** [comment]
Was somehow related to DKIM, which is simply too long for 1 TXT. No fix as of now...

**Comment by HLFH** [comment]
I think the comment in `StackExchange/dnscontrol/blob/fix-ovh-dmarc-txt/providers/ovh/protocol.go` could be wrong.

```
			// When DKIM value is longer than 255, the MODIFY fails with "Try to alter read-only properties: fieldType"
			// Setting FieldType to empty string results in the property not being altered, hence error does not occur.
```
You also get these errors with SPF and DMARC records because OVH does not show them as TXT RR but as DMARC and SPF RR.

In `StackExchange/dnscontrol/blob/fix-ovh-dmarc-txt/providers/ovh/ovhProvider.go`, after my PR https://github.com/StackExchange/dnscontrol/pull/2485 is merged for DMARC custom RR, it will say:
```
	// ovh uses a custom type for SPF, DKIM and DMARC
	if rtype == "SPF" || rtype == "DKIM" || rtype == "DMARC" {
		rtype = "TXT"
	}
```
And, so, after this PR, the parsing with `get-zones` will work but not the `dnscontrol push`, so some code needs to be changed.
