### ISSUE TITLE
Idea: Moving from vendor to modules

### ISSUE THREAD

**Issue by kochie** [StackExchange/dnscontrol#500]
I'm sure people have seen the [introduction of modules to Go](https://blog.golang.org/using-go-modules). Just wondering if this is something that dnscontrol will move over to in the near future?

I think the biggest advantage to using modules is no longer needing to commit dependencies to `vendor/` which can increase the size of the project and requires constant updating. Are there any reasons why it wouldn't be a good idea to move to modules?

**Comment by captncraig** [comment]
Thanks for bringing this up.

Gonna be honest, I have not used any projects with modules yet, and I don't fully understand how they work or what the workflow looks like. 

That being said, I do like a number of things that vendoring gives us:

1. The code can always be built from a fresh clone. No external tools or extra fetches need be made.
2. Auditability. I can look at specific changes and see what they change as we update dependencies. DnsControl could do some really damaging things if compromised, so I tend to look closely at dependency updates depending on the source.
3. Explicitness. I appreciate that specific versions are chosen and no variance is allowed. I know rsc had a whole blog post explaining the ideas of semantic versioning and fuzzy matching and whatever md does, but I feel kinda comfortable having fixed versions.
4. I know the tooling behind govendor pretty well and am a bit resistant to change at this point once I've found a system that mostly works.

The increased size of the vendor folder is unfortunate, but it really doesn't bother me that much.

Yes, I need to be more diligent at updating packages when updates are available.

**Comment by captncraig** [comment]
All that being said, it seems modules are the way the wind is blowing, and I've been avoiding them too long. I'm gonna make a point to convert this project and see if I can't work out some of my reluctance.

**Comment by kochie** [comment]
Those are some good points. It looks like modules will support [keeping the dependencies in a vendor folder still](https://github.com/golang/go/wiki/Modules#how-do-i-use-vendoring-with-modules-is-vendoring-going-away), which should at least help with the issues you raised.

**Comment by captncraig** [comment]
Well I'm sold primarily based on being able to ditch the gopath concept altogether.

I'd like to try out modules with vendoring and see what really changes. 

Unfortunately this project has become a bit of a tangled web. Some dependencies don't exist anymore or have been renamed. Others have made major breaking changes. Gotta figure out how to bring everything up to date as easily as possible, then switch to modules.

**Comment by Shinzu** [comment]
on a branch on my [fork](https://github.com/Shinzu/dnscontrol/tree/use-go-modules) i switched to go modules since i wanted to update the [dns package](https://github.com/miekg/dns) (needed a newer version that supports $GENERATE for the convertzone cmd)

Worked pretty well so far, but have to test it further, fell free to try it out

the good think with go modules is, via a simple `go get github.com/miekg/dns@v1.0.15` i could switch to the version that i wanted, afterwards i had to adjust some dependencies but this then can be done the same way.

**Comment by geek1011** [comment]
Go modules have come a really long way, and I feel they are quite usable now. I've switched most of my own projects over.

@captncraig, In response to your points about vendoring:
1. It is even easier to build from a fresh clone with modules, as you don't need to worry about where you put the code. Go will automatically manage the dependencies.
2. If you wish, you can still use `go mod vendor` to vendor the dependencies in the same way.
3. It is even more explicit with modules for a few reasons. Firstly, the versions are fixed and the fuzziness only applies when manually updating dependencies. Secondly, the actual code itself is hashed into go.sum, so you can't make changes. Thirdly, you can't change the code used to build without an explicit `replace` directive. Fourthly, even if the original source disappears or is force-pushed, you can still access it with something like `proxy.golang.org`.
4. The workflow is pretty much the same. Just use `go mod init` instead of `govendor init`, `go get` instead of `govendor fetch`, `go mod download; go mod vendor` instead of `govendor sync`, and run `go mod tidy` afterwards to clean things up.

**Comment by captncraig** [comment]
I will do this soon for the next major release (after the one we will be making in the next day or 2).

**Comment by tlimoncelli** [comment]
Done in 16d0043cce7aeb5d52cb17f023fd625c2fd02ddb
