### ISSUE TITLE
Add a NONE providers for DNS.

### ISSUE THREAD

**Issue by tlimoncelli** [StackExchange/dnscontrol#601]
This exists for Registrars but not DNS Providers.  Having one for DNS would be beneficial for people that just want to control registration lock.

**Comment by captncraig** [comment]
Is this really needed? The "None" registrar exists because every domain must declare a registrar. A domain can have between 0 and N dns providers though. The only effect dns providers have on the registrar, is providing a list of nameservers, which can also be done manually.

 If you don't have a dns provider, or have a non-supported one, but still want to use dnscontrol for the registrar, you can just omit the dnspovider and supply `NAMESERVER` records as needed. What else would be needed?

**Comment by tlimoncelli** [comment]
Ah, I forgot that there could be 0 dns providers. 

There's a new registrar-only provider and to make the example in the docs look clean by having a NONE provider... but listing no providers is better. Thanks!

(see https://github.com/StackExchange/dnscontrol/pull/590)
