### ISSUE TITLE
Dyn

### ISSUE THREAD

**Issue by mattrobenolt** [StackExchange/dnscontrol#61]
Dyn is pretty big and would be nice to have support. <3

If nobody is inclined, I may dig deeper into the code and see if I can implement this myself.

**Comment by captncraig** [comment]
Dyn would definitely be nice to support. Have not implemented it yet because we don't use it presently, but it would certainly be nice to have. Their api seems to be sufficient to support most things easily, possibly using https://github.com/nesv/go-dynect.

My main hangup initially is that there does not appear to be any kind of free tier or api sandbox. Makes it hard to develop a client without paying for a monthly plan.

**Comment by mattrobenolt** [comment]
Cool, I might work on this since we have an account. I have no idea if there's a way to get a testing account just to test or play.

**Comment by captncraig** [comment]
Looks like dyn has graciously set us up with a test account we can use to develop this. I should be able to make progress on this as I get some free time.

**Comment by gibson042** [comment]
If you need any help, please don't hesitate to reach out. Some aspects of api.dynect.net can be quite surprising, but its replacement isn't yet ready for public consumption.

**Comment by tibu** [comment]
Did anyone make any progress on this? I would be happy to contribute.

**Comment by tibu** [comment]
OK, I see now https://github.com/StackExchange/dnscontrol/pull/83

**Comment by captncraig** [comment]
Yeah, I don't really have any blockers on merging that, so I'd love any feedback if you can run it. We just don't use dyn so it hasn't been a priority.

**Comment by tlimoncelli** [comment]
Hi!  I'm sorry this issue got lost.  How is this going?  Can we continue where we left off?

**Comment by mattrobenolt** [comment]
Well, Dyn is shutting down in a few months, so probably not worth it now.

**Comment by tlimoncelli** [comment]
Oh geez.  I didn't hear about that.  I'm equally embarrassed that I didn't know and sad to see them go.
