### ISSUE TITLE
Provider Request: deSEC

### ISSUE THREAD

**Issue by Knight1** [StackExchange/dnscontrol#724]
Hi!

The non-profit DNS Provider deSEC.de from Germany is now out of beta 🥳

Can you please implement their API https://desec.readthedocs.io?

Thanks!

**Comment by D3luxee** [comment]
I've started working on this today, because deSEC seems nice but they don't provide any frontend (or i did not find it).
And using curl for dns management looks painful.

**Comment by peterthomassen** [comment]
It's great to see the community interest in deSEC! If you have any questions during implementation of the dnscontrol plugin, please don't hesitate to get in touch with or mention @nils-wisiol or myself.

**Comment by D3luxee** [comment]
Hi @peterthomassen,
i've got my first WIP version running and now im facing a rate limiting on your api:
`FAILURE! Error create rrset deSEC: http status 429 429 Too Many Requests details: Request was throttled. Expected available in 1 second.`
I was just creating 10 records with dnscontrol which was enough to trigger your rate limit.

Do you have informations about the parameters of the rate limiting?

**Comment by peterthomassen** [comment]
Hi! You can find the throttle parameters here: https://github.com/desec-io/desec-stack/blob/master/api/api/settings.py#L115-L124

If you want to create several records, would it be possible for you to send them all as a bulk request? That would count as just one request with regards to rate limiting. Here are the relevant docs: https://desec.readthedocs.io/en/latest/dns/rrsets.html#bulk-operations

**Comment by D3luxee** [comment]
Hi,
bulk operations are not easy to implement due to the way how dnscontrol works. 
The correction made by dnscontrol are individual actions on specific rrsets: https://github.com/StackExchange/dnscontrol/blob/26abff8884d43f4c2a312d123baab4f774b2add4/models/provider.go#L6 at least thats how it is implemented in the interface.

Currently im working on some workaround for the rate limiting (retry / backoff time).

**Comment by D3luxee** [comment]
@Knight1 i've created a pull request, feel free to build it and test the deSEC provider.

**Comment by peterthomassen** [comment]
@D3luxee Sorry to hear that bulk requests are not straightforward in dnscontrol. Unfortunately, those API requests which add/modify/remove RRsets are the most expensive ones we have, due to the signing requirement we have. With very larger zones (~100k records), signing can take a few seconds, and we want to avoid processing write requests in quick succession to avoid failures due to race conditions etc. In other words, the rate limit is in the interest of stability, not just resources usage, and I'm afraid we can't really change the concept right now (although we may adapt the number of requests allowed depending on the circumstances).

However, I imagine that bulk requests would also be a beneficial thing for dnscontrol as far as other DNS providers are concerned. At least that's how it seems to me. Wouldn't that perhaps be a good moment to try tackling this problem conceptually in dnscontrol?

**Comment by tlimoncelli** [comment]
Some providers do bulk updates.  Can I help you with that?

What kind of bulk updates are permitted?

**Comment by tlimoncelli** [comment]
Ah, I just answered my own question by reading the docs at https://desec.readthedocs.io/en/latest/dns/rrsets.html#bulk-operations :-)

You could combine all the adds/changes/deletes into one PUT.  

Take the output of `IncrementalDiff()` and group the results by label:rtype (similar to what `ChangedGroups()` does, but the result should be `map[models.RecordKey][]Changeset`.

Now iterate over the list to generate the array of RRset objects.  For each add output the new records.  For each delete output an empty "records".  Changes might be more difficult since you need to know what used to be there.

gandi_v5/gandi_v5Provider.go does something similar.

**Comment by peterthomassen** [comment]
> Changes might be more difficult since you need to know what used to be there.

If you use `PATCH`, you can send leaner requests / requests with less knowledge (e.g. to change a TTL value, you don't need to resend the record contents and vice versa). All valid `PUT` requests are also valid for `PATCH`. Not sure if this is what you meant by "know what used to be there".

**Comment by tlimoncelli** [comment]
Yes, PATCH would make the requests a bit smaller.  However, I don't recommend using it.

Dnscontrol's diffing algorithm is very "all or none": Either something about the record changed or nothing did.  This works fine for all providers whether they need updates per record, per rrset, or per zone.

If you want to determine which specific fields changed (TTL, target, etc.), you'd have to write a custom diffing algorithm which would be more fine-grained and could generate more specific PATCH data.  However, that would be a lot of work and would require a lot of testing.  It would also need to be updated every time someone adds a new record type, which is rather frequent.  On the other hand, it is rather rare that someone changes just the TTL, for example.  Also, the DNS Provider is already determining these smaller changes.

Therefore I recommend PUT and let the provider figure out which fields changed.

**Comment by D3luxee** [comment]
> Ah, I just answered my own question by reading the docs at https://desec.readthedocs.io/en/latest/dns/rrsets.html#bulk-operations :-)
> 
> You could combine all the adds/changes/deletes into one PUT.
> 
> Take the output of `IncrementalDiff()` and group the results by label:rtype (similar to what `ChangedGroups()` does, but the result should be `map[models.RecordKey][]Changeset`.
> 
> Now iterate over the list to generate the array of RRset objects. For each add output the new records. For each delete output an empty "records". Changes might be more difficult since you need to know what used to be there.
> 
> gandi_v5/gandi_v5Provider.go does something similar.

I will take a look into this, it would be nice if i can merge the requests into one bulk.
Thanks for this hint.

**Comment by D3luxee** [comment]
@tlimoncelli 
My problem is how can i reflect this using "[]*models.Correction" because this handles the messages / output too, currently i do one request per models.RecordKey.
Technically its not problem to merge all changes into one single api request, but this would result in one models.Correction.
How can i get dnscontrol to print the messages of each change but call only one function once.

**Comment by tlimoncelli** [comment]
`Msg` can have newlines.  You can just stuff all the messages you want into the string.  If you look at the BIND driver, it builds up all the messages in `buf` then uses it to create the `Msg` in a single change.

**Comment by D3luxee** [comment]
> `Msg` can have newlines. You can just stuff all the messages you want into the string. If you look at the BIND driver, it builds up all the messages in `buf` then uses it to create the `Msg` in a single change.

Thanks, i will take a look at it and start implementing it using bulk requests.

**Comment by D3luxee** [comment]
@peterthomassen @tlimoncelli after the hint regarding the message it was pretty easy to implement it with just one single bulk request for all changes.
You can take a look at it here d30cfc0
