### ISSUE TITLE
GCLOUD: Support DS records

### ISSUE THREAD

**Issue by tlimoncelli** [StackExchange/dnscontrol#762]
Hi @mhuxtable !  Sadly I had to revert the PR.

Here's the error I'm seeing:

```
$ go test -v -verbose -provider GCLOUD -start 24 -end 24 -run TestDNSProviders
=== RUN   TestDNSProviders
=== RUN   TestDNSProviders/dnscontroltest-gcloud.com
=== RUN   TestDNSProviders/dnscontroltest-gcloud.com/Clean_Slate:Empty
=== RUN   TestDNSProviders/dnscontroltest-gcloud.com/24:DS:create_DS
    TestDNSProviders/dnscontroltest-gcloud.com/24:DS:create_DS: integration_test.go:179: CREATE DS dnscontroltest-gcloud.com 1 13 1 ADIGEST ttl=300
        
    TestDNSProviders/dnscontroltest-gcloud.com/24:DS:create_DS: integration_test.go:183: googleapi: Error 400: Invalid value for 'entity.change.additions[0].rrdata[0]': '1 13 1 ADIGEST', invalid
=== RUN   TestDNSProviders/dnscontroltest-gcloud.com/Post_cleanup:Empty
--- FAIL: TestDNSProviders (1.01s)
    --- FAIL: TestDNSProviders/dnscontroltest-gcloud.com (0.61s)
        --- PASS: TestDNSProviders/dnscontroltest-gcloud.com/Clean_Slate:Empty (0.18s)
        --- FAIL: TestDNSProviders/dnscontroltest-gcloud.com/24:DS:create_DS (0.29s)
        --- PASS: TestDNSProviders/dnscontroltest-gcloud.com/Post_cleanup:Empty (0.14s)
FAIL
exit status 1
FAIL	github.com/StackExchange/dnscontrol/v3/integrationTest	1.298s
```

**Comment by tlimoncelli** [comment]
I updated all the Google-related dependencies. Sadly that didn't fix it.  At least we know it isn't a dependency problem.

**Comment by mhuxtable** [comment]
Hmm, strange. No worries, I'll have a look into it.

**Comment by mhuxtable** [comment]
Looks like the problems here are two-fold:
(also, apologies for not spotting the integration test suite before. I went searching for anything in the readme about guides to follow for contributors but never checked the repo <d'oh>):

- Google Cloud DNS is not a registrar so does not support `DS` records at the root. This restriction is enforced by the API. They are only supported on child domains to enable secured delegations to other nameservers.
- The API appears to enforce that the digest contains only hex characters, but the tests provide the digest value `ADIGEST`.

   [The RFC currently specifies the only supported algorithm for producing the digest involves a SHA-1 hash](https://tools.ietf.org/html/rfc4034#section-5.1.4) is supported for producing the digest, so the restriction currently makes some sense. It would appear other algorithms may be supported in future in which case the character set may later be expanded broader than the typical SHA-1 output alphabet. Either way I doubt I'll influence changes to the Cloud DNS API anytime soon, so we'll have to work around this.

I can make the tests pass by commenting out the tests which clash with the API invariants. Here's a possible route to resolution for this:

- Introduce a new capability `CanUseDSForChildren` which indicates a provider supports record sets of type `DS` for child zones only. `CanUseDS` would (could) imply `CanUseDSForChildren` is true for simplicity.
- Update the digest in the tests to use an arbitrary hex value, say `0123456789ABCDEF`
- Bifurcate the tests to test only child record creation in the case of the new capability, and run the full suite otherwise.

Concerns:

- I don't have the ability to run all the integration test suites locally so would need some co-ordination on this change. My change to the digest value may impact all providers. I'm setting it to a valid value, so hopefully all is fine, but I'd need to be sure.
- This creates some interdependence between provider capabilities which don't appear to currently exist.

Grateful for your thoughts. I'm happy to work on this – I'm in the process of codifying our DNS specifications in source code and have built a flow around DNSControl, so happy to resolve any and all blocking issues so we can progress that work.

Thanks.

**Comment by tlimoncelli** [comment]
Great writeup! Very clear!  Thanks! 

* Google Cloud DNS is not a registrar so does not support DS records at the root. 

I think it is reasonable to have 2 Capabilities as DS-for-all and DS-for-subs seem to be two different categories.

* The API appears to enforce that the digest contains only hex characters

Yeah, I just threw in any string.  We should definitely use all hex.

**Comment by mhuxtable** [comment]
Great! I'll get back tomorrow with a patch.

**Comment by mhuxtable** [comment]
I've put that changeset together in #765, better late than never.
