### ISSUE TITLE
Route53 MODIFY only modifies 1 record instead of all

### ISSUE THREAD

**Issue by mludvig** [StackExchange/dnscontrol#891]
I'm bringing a number of our zones under _dnscontrol_ and realised that some of them have records with a missing trailing dot. Although _Route53_ doesn't seem to mind and resolves them correctly _dnscontrol_ complains. However when I fix the records in `dnsconfig.js` in each run `dnscontrol` only fixes one record.

This is what was fetched by `dnscontrol get-zone`, the trailing dots are actually missing in our Route53 zone:

```
	CNAME('test1', 'test1.example.com'),
	CNAME('test2', 'test2.example.com'),
	CNAME('test3', 'test3.example.com'),
```

The same file can't be previewed and pushed: "ERROR: in CNAME test1.smarterdata.nz: target (test1.example.com) must end with a (.)" - that's ok. 

So I add the trailing dots, preview and push:

```
/dns # dnscontrol push --domains smarterdata.nz
******************** Domain: smarterdata.nz
----- Getting nameservers from: Route53
----- DNS Provider: Route53...1 correction
#1: 
MODIFY CNAME test2.smarterdata.nz: (test2.example.com ttl=300) -> (test2.example.com. ttl=300)
MODIFY CNAME test3.smarterdata.nz: (test3.example.com ttl=300) -> (test3.example.com. ttl=300)
MODIFY CNAME test1.smarterdata.nz: (test1.example.com ttl=300) -> (test1.example.com. ttl=300)
SUCCESS!
----- Registrar: DiscountDomains...0 corrections
Done. 1 corrections.
```

However by now only one record has been updated. It's not a timing issue, any amount of waiting doesn't matter. **I have to run push 3x to update them all.**

```
/dns # dnscontrol push --domains smarterdata.nz
******************** Domain: smarterdata.nz
----- Getting nameservers from: Route53
----- DNS Provider: Route53...1 correction
#1: 
MODIFY CNAME test2.smarterdata.nz: (test2.example.com ttl=300) -> (test2.example.com. ttl=300)
MODIFY CNAME test3.smarterdata.nz: (test3.example.com ttl=300) -> (test3.example.com. ttl=300)
SUCCESS!
----- Registrar: DiscountDomains...0 corrections
Done. 1 corrections.


/dns # dnscontrol push --domains smarterdata.nz
******************** Domain: smarterdata.nz
----- Getting nameservers from: Route53
----- DNS Provider: Route53...1 correction
#1: 
MODIFY CNAME test3.smarterdata.nz: (test3.example.com ttl=300) -> (test3.example.com. ttl=300)
SUCCESS!
----- Registrar: DiscountDomains...0 corrections
Done. 1 corrections.


/dns # dnscontrol push --domains smarterdata.nz
******************** Domain: smarterdata.nz
----- Getting nameservers from: Route53
----- DNS Provider: Route53...0 corrections
----- Registrar: DiscountDomains...0 corrections
Done. 0 corrections.
/dns # 
```

I use *dnscontrol 3.3.0* from docker image stackexchange/dnscontrol pulled today.

```
/dns # dnscontrol version
dnscontrol 3.3.0 ("51b3a5ee0badcd9ec611fc6e6076eefcf6249541[dirty]") built 07 Oct 20 20:39 UTC
```

**Comment by tlimoncelli** [comment]
Very interesting!

I'm having trouble reproducing these.  Can you   Can you try again with the latest "master" branch?

**The CNAMEs not updating on the first try:**  I don't think it is a timing issue as the Route 53 API reflects the source of truth, even if those changes haven't propagated out to the internet yet.   My guess is related to the next issue.

**The CNAME issue with get-zones:**  The goal of get-zone is to create a "reasonable first draft".  That said, it should put the "." at the end of those CNAME targets.  As a test, I just did a "get-zone" on a R53 domain and I got the expected output (a "." at the end).

Here's what I think is happening:

Route 53 used to be "helpful" with certain user mistakes.  For example, a CNAME target "whatever.com" was assumed to be a typo, so R53 would helpfully act as if you included a "." at the end.  It made reasonable guesses for domains ending with `.com` and other TLDs.

This works great... until it doesn't.  Eventually a customer has a short-name that ends with `.com`, complains, and soon R53 realizes it isn't helpful to silence correct people's mistakes.  Many DNS providers have gone through this.  In fact, 1.0 of DNSControl tried to be "smart" like that, and it backfired for the same reasons. That's why we're so strict about CNAME targets now.

R53 still respects the old behavior for DNS records created under the old rules.  Those records download as dotless in their API.  The API doesn't reveal if that's a record which lives by the old rules, thus the dotless CNAME is generated. However if you manually add the dot, things should work fine.

I don't know why it took 3 pushes to fix the problem. I assume it is some strange interaction with the old API trying to be compatible with the old way?

My suggestion is to update your dnsconfig.js with the proper dots and let dnscontrol do its updates. The problem will go away after that. 

Tom

**Comment by mludvig** [comment]
Hi, yeah it's not a question about the need for a trailing dot, I understand that. It's more about why only one record at a time is updated and not all.

Steps to reproduce:

1. Create a new Hosted Zone (e.g. `test.tld`)
2. Create 3 CNAMEs in it, all without a trailing dot, e.g. `test1 CNAME test1.example.com`, `test2 CNAME test2.example.com`, `test3 CNAME test3.example.com`
3. Pull the zone: `dnscontrol get-zone r53 ROUTE53 test.tld`
4. Add the trailing dots for all 3 records to make it `CNAME('test1', 'test1.example.net.')`, same for `test2` and `test3`.
5. Push the changes - note that only one change has been actioned.
6. Run `dnscontrol push` 3x to add all the trailing dots.

Verified the above steps right now with `dnscontrol` build from v3 source.

**Comment by pgaskin** [comment]
> I'm having trouble reproducing these. Can you Can you try again with the latest "master" branch?

> I assume it is some strange interaction with the old API trying to be compatible with the old way?

I'm not familiar with Route53, but it's likely that this issue is caused by the same thing as #890 (see https://github.com/StackExchange/dnscontrol/issues/890#issuecomment-705888871). If @mludvig is using a build with plain `go get` or building from source within `GOPATH` without `GO111MODULE=on`, it will use the dependency versions in `GOPATH` rather than the ones specified in `go.mod`.

@mludvig, can you try reproducing this issue with a binary built using `GO111MODULE=on go get github.com/StackExchange/dnscontrol/v3` or built from source in a folder *outside* the `GOPATH`?

**Comment by mludvig** [comment]
> can you try reproducing this issue with a binary built using GO111MODULE=on go get github.com/StackExchange/dnscontrol/v3 or built from source in a folder outside the GOPATH?

Yes I did. It's the same both with GO111MODULES=on and also using your official docker container pulled from docker hub. I doubt it's got anything to do with the way my binary was built.

**Comment by tlimoncelli** [comment]
Hi @mludvig!

I was able to reproduce the problem. Thank you for the excellent write up!

It looks like DnsControl sends 3 UPSERT commands but for some reason only the first one executes.

Here's the output when I add a Printf to show the change command being generated.

```
$ ~/bin/dnscontrol preview
******************** Domain: dnscontroltest-r53.com
----- Getting nameservers from: r53
----- DNS Provider: r53...CHANGEREQ={
  ChangeBatch: {
    Changes: [{
        Action: "UPSERT",
        ResourceRecordSet: {
          Name: "test1.dnscontroltest-r53.com",
          ResourceRecords: [{
              Value: "test1.example.com."
            }],
          TTL: 300,
          Type: "CNAME"
        }
      },{
        Action: "UPSERT",
        ResourceRecordSet: {
          Name: "test2.dnscontroltest-r53.com",
          ResourceRecords: [{
              Value: "test2.example.com."
            }],
          TTL: 300,
          Type: "CNAME"
        }
      },{
        Action: "UPSERT",
        ResourceRecordSet: {
          Name: "test3.dnscontroltest-r53.com",
          ResourceRecords: [{
              Value: "test3.example.com."
            }],
          TTL: 300,
          Type: "CNAME"
        }
      }]
  }
}
```

It looks correct to me.  If this is a bug on AWS, we can update the docs to warn people about this.

**Comment by mludvig** [comment]
You're right @tlimoncelli, verified with _aws cli_ and it exhibits the same issue. It's not `dnscontrol`'s fault :)
I'll report it to Amazon. Thanks for your help with this.

**Comment by tlimoncelli** [comment]
Great!  If AWS gives you a bugid or other tracking number please let me know. I'll add it to #901
