### ISSUE TITLE
Idea: support fetch external resources over HTTP

### ISSUE THREAD

**Issue by xddxdd** [StackExchange/dnscontrol#994]
Fetching external resources and parsing them in dnsconfig.js will be very useful, for example get a list of nodes from your cloud provider and automatically set up DNS for all of them.

There's an extension for otto https://github.com/deoxxa/ottoext which implements an event loop, fetch and a few other things, and seems straightfoward to integrate.

**Comment by tlimoncelli** [comment]
Hi there!

Interesting idea.  I'm not sure I totally understand how this would be used.  Could you give an example or two?

**Comment by xddxdd** [comment]
@tlimoncelli For example, I may have a few servers with a cloud provider, and I want to set DNS records to them:

DB -> 1.1.1.1
Web -> 1.1.1.2

And so on. The problem is that I may add, remove, or repurpose servers from time to time, and each time I do such change, I have to update the config of dnscontrol manually. This creates two sources of truth and is error-prone.

This problem can be fixed if dnscontrol can get the mapping from my provider's API, and create records for all servers.

**Comment by tlimoncelli** [comment]
In an ideal world, what would the syntax look like?

**Comment by xddxdd** [comment]
The syntax would be similar to:

```
fetch('https://api.example.com').then(function(r) {
        return r.text();
}).then(function(r) {
        console.log(r);
        // Add DNS records
});
```

This is the same fetch API used by browsers (https://developer.mozilla.org/en-US/docs/Web/API/Fetch_API).

**Comment by tlimoncelli** [comment]
That's an interesting use-case!  I hadn't thought of that kind of thing before.

How would `fetch()` work when it fails?  I'd hate to be stranded and not able to do DNS updates because some API is having a temporary outage.  Currently dnscontrol's compilation phase has zero external dependencies.  For example, SPF optimizer caches all DNS requests so that future updates won't fail if DNS is inaccessible.  fetch would need a similar cache mechanism.

Until this feature is implemented, there is a simple work-around.  You could "curl" the URL to a file then use `r = require("filename.json")`.  If  the path string ends with `.json`, `require()` returns the `JSON.parse()` of the file's contents.  A Makefile or shell script is a good way to make sure that the curl always happens.

**Comment by xddxdd** [comment]
`fetch()` returns a Promise, so standard Promise.catch will work with it:

```
fetch('http://nonexistent.com').then(function(r) {
	return r.text();
}).then(function(r) {
	console.log(r);
        // do stuff with the result
}).catch(function(e) {
	console.log(e);
        // do stuff when things fail
});
```

However right now dnscontrol lacks some useful ability to handle errors, such as removing a domain, or a function to declare that the result of this run shouldn't be applied.

Personally I think that the DNS update process should fail if the API doesn't work, since:

1. Dnscontrol is designed to replace the records of a domain. If the API fails there's no way to reliably know which records previously belong to the API and should not be removed.
2. Caching masks problems until it's too late. One of dnscontrol's design goal is to be run in an automated manner such as a CI/CD, which means if caching is used by default, it may take a long time for the user to notice that the API failed, and dnscontrol is generating records based on old data.

Of course dnscontrol can provide means/functions to cache API results, if the user is aware of the consequences. But in my opinion this is an enhancement, not a necessity.

**Comment by tlimoncelli** [comment]
I agree with your analysis.  "Fast fail" is better than a complicated caching mechanism.
